import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:multi_split_view/multi_split_view.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'shared_dynamic_table.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;

import '../providers/request_provider.dart';
import '../providers/settings_provider.dart';
import 'save_request_dialog.dart';
import 'app_code_editor.dart';
import 'package:post_lens/presentation/widgets/common/custom_controls.dart';

class SocketMessage {
  final String content;
  final bool isSent;
  final DateTime timestamp;
  final String? eventName;

  SocketMessage(this.content, this.isSent, this.timestamp, {this.eventName});
}

class SocketPane extends ConsumerStatefulWidget {
  const SocketPane({super.key});

  @override
  ConsumerState<SocketPane> createState() => _SocketPaneState();
}

class _SocketPaneState extends ConsumerState<SocketPane>
    with SingleTickerProviderStateMixin {
  static const double _compactTableRowHeight = 28;
  static const double _compactTableOuterHorizontalPadding = 6;
  static const double _compactTableCellHorizontalPadding = 4;
  static const double _compactTableColumnGap = 6;
  static const double _compactTableSideSlotWidth = 28;
  static const double _compactTableLeadingSlotWidth = 22;
  static const double _compactSectionTopSpacing = 12;
  static const double _compactSectionLabelGap = 6;

  final TextEditingController _urlController = TextEditingController();
  final FocusNode _urlFocusNode = FocusNode();

  // Message Tab
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  final TextEditingController _eventNameController = TextEditingController();
  bool _ack = false;
  String _argType = 'Text'; // 'Text', 'JSON'
  List<Map<String, dynamic>> _args = [
    {'id': '1', 'name': 'Arg 1', 'content': ''}
  ];
  int _selectedArgIndex = 0;

  // Events Tab
  List<Map<String, dynamic>> _events = [];

  // Params Tab
  List<Map<String, String>> _params = [];

  // Headers Tab
  List<Map<String, String>> _headers = [];
  bool _hideAutoGeneratedHeaders = false;

  // Settings Tab
  bool _verifyCertificate = false;
  String _clientVersion = 'v3';
  final TextEditingController _handshakePathController =
      TextEditingController(text: '/socket.io');
  final TextEditingController _timeoutController =
      TextEditingController(text: '0');
  final TextEditingController _reconnectAttemptsController =
      TextEditingController(text: '0');
  final TextEditingController _reconnectIntervalController =
      TextEditingController(text: '5000');

  late TabController _tabController;

  bool _isConnected = false;
  bool _isProtocolHovered = false;
  final List<SocketMessage> _messages = [];

  IO.Socket? _socket;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 5, vsync: this);
    _urlFocusNode.addListener(() => setState(() {}));
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final req = ref.read(requestProvider);
      if (req.url.isNotEmpty) {
        _urlController.text = req.url;
      }
      if (req.settings.containsKey('socketSettings')) {
        final s = req.settings['socketSettings'];
        if (s['verifyCertificate'] != null)
          _verifyCertificate = s['verifyCertificate'];
        if (s['clientVersion'] != null) _clientVersion = s['clientVersion'];
        if (s['handshakePath'] != null)
          _handshakePathController.text = s['handshakePath'];
        if (s['timeout'] != null)
          _timeoutController.text = s['timeout'].toString();
        if (s['reconnectAttempts'] != null)
          _reconnectAttemptsController.text = s['reconnectAttempts'].toString();
        if (s['reconnectInterval'] != null)
          _reconnectIntervalController.text = s['reconnectInterval'].toString();
      }
      if (req.settings.containsKey('socketEvents')) {
        _events = List<Map<String, dynamic>>.from(req.settings['socketEvents']
            .map((e) => Map<String, dynamic>.from(e)));
      }
      if (req.settings.containsKey('socketArgs')) {
        _args = List<Map<String, dynamic>>.from(req.settings['socketArgs']
            .map((e) => Map<String, dynamic>.from(e)));
        if (_args.isEmpty) {
          _args = [
            {'id': '1', 'name': 'Arg 1', 'content': ''}
          ];
        }
      }
      if (req.settings.containsKey('socketArgType')) {
        _argType = req.settings['socketArgType'];
      }
      if (req.settings.containsKey('socketAck')) {
        _ack = req.settings['socketAck'];
      }
      if (req.settings.containsKey('socketEventName')) {
        _eventNameController.text = req.settings['socketEventName'];
      }
      setState(() {
        _params = List<Map<String, String>>.from(
            req.params.map((e) => Map<String, String>.from(e)));
        _headers = List<Map<String, String>>.from(
            req.headers.map((e) => Map<String, String>.from(e)));
      });
    });
  }

  @override
  void dispose() {
    _socket?.dispose();
    _urlController.dispose();
    _urlFocusNode.dispose();
    _messageController.dispose();
    _scrollController.dispose();
    _eventNameController.dispose();
    _handshakePathController.dispose();
    _timeoutController.dispose();
    _reconnectAttemptsController.dispose();
    _reconnectIntervalController.dispose();
    _tabController.dispose();
    super.dispose();
  }

  void _saveSettings() {
    final req = ref.read(requestProvider);
    final s = Map<String, dynamic>.from(req.settings);
    s['socketSettings'] = {
      'verifyCertificate': _verifyCertificate,
      'clientVersion': _clientVersion,
      'handshakePath': _handshakePathController.text,
      'timeout': int.tryParse(_timeoutController.text) ?? 0,
      'reconnectAttempts': int.tryParse(_reconnectAttemptsController.text) ?? 0,
      'reconnectInterval':
          int.tryParse(_reconnectIntervalController.text) ?? 5000,
    };
    s['socketEvents'] = _events;
    s['socketArgs'] = _args;
    s['socketArgType'] = _argType;
    s['socketAck'] = _ack;
    s['socketEventName'] = _eventNameController.text;
    ref.read(requestProvider.notifier).updateAllSettings(s);
  }

  void _toggleConnection() {
    final t = ref.read(translationsProvider);
    if (_isConnected) {
      _socket?.disconnect();
      setState(() {
        _isConnected = false;
        _messages.add(SocketMessage(
            t['disconnected'] ?? 'Disconnected', false, DateTime.now()));
      });
    } else {
      try {
        final url = _urlController.text;

        final opts = IO.OptionBuilder()
            .setTransports(['websocket'])
            .disableAutoConnect()
            .setPath(_handshakePathController.text.isNotEmpty
                ? _handshakePathController.text
                : '/socket.io');

        final timeout = int.tryParse(_timeoutController.text) ?? 0;
        if (timeout > 0) opts.setTimeout(timeout);

        final attempts = int.tryParse(_reconnectAttemptsController.text) ?? 0;
        opts.setReconnectionAttempts(attempts);

        final interval =
            int.tryParse(_reconnectIntervalController.text) ?? 5000;
        opts.setReconnectionDelay(interval);

        _socket = IO.io(url, opts.build());

        _socket!.onConnect((_) {
          if (mounted) {
            setState(() {
              _isConnected = true;
              _messages.add(SocketMessage(
                  '${t['connected_to'] ?? 'Connected to'} $url',
                  false,
                  DateTime.now()));
            });
            _scrollToBottom();
          }
        });

        _socket!.onDisconnect((_) {
          if (mounted) {
            setState(() {
              _isConnected = false;
              _messages.add(SocketMessage(
                  t['disconnected_from'] ?? 'Disconnected from server',
                  false,
                  DateTime.now()));
            });
            _scrollToBottom();
          }
        });

        _socket!.onConnectError((err) {
          if (mounted) {
            setState(() {
              _messages.add(SocketMessage(
                  '${t['connect_error'] ?? 'Connect Error'}: $err',
                  false,
                  DateTime.now()));
            });
            _scrollToBottom();
          }
        });

        _socket!.onError((err) {
          if (mounted) {
            setState(() {
              _messages.add(SocketMessage(
                  '${t['connect_error'] ?? 'Error'}: $err',
                  false,
                  DateTime.now()));
            });
            _scrollToBottom();
          }
        });

        // Listen to custom events
        for (var ev in _events) {
          if (ev['listen'] == true && ev['name']?.isNotEmpty == true) {
            _socket!.on(ev['name'], (data) {
              if (mounted) {
                setState(() {
                  _messages.add(SocketMessage(
                      data.toString(), false, DateTime.now(),
                      eventName: ev['name']));
                });
                _scrollToBottom();
              }
            });
          }
        }

        // Also listen to default 'message' event
        _socket!.on('message', (data) {
          if (mounted) {
            setState(() {
              _messages.add(SocketMessage(
                  data.toString(), false, DateTime.now(),
                  eventName: 'message'));
            });
            _scrollToBottom();
          }
        });

        _socket!.connect();
      } catch (e) {
        setState(() {
          _messages.add(SocketMessage(
              '${t['failed_to_connect'] ?? 'Failed to initialize connection'}: $e',
              false,
              DateTime.now()));
        });
      }
    }
  }

  void _sendMessage() {
    final t = ref.read(translationsProvider);
    if (!_isConnected) return;

    final evt = _eventNameController.text.isNotEmpty
        ? _eventNameController.text
        : 'message';

    // Collect args
    List<dynamic> dataToSend = [];
    for (var arg in _args) {
      if (arg['content'].isNotEmpty) {
        if (_argType == 'JSON') {
          try {
            dataToSend.add(jsonDecode(arg['content']));
          } catch (e) {
            dataToSend.add(arg['content']);
          }
        } else {
          dataToSend.add(arg['content']);
        }
      }
    }

    dynamic payload;
    if (dataToSend.isEmpty) {
      return; // Nothing to send
    } else if (dataToSend.length == 1) {
      payload = dataToSend[0];
    } else {
      payload = dataToSend;
    }

    setState(() {
      _messages.add(SocketMessage(jsonEncode(payload), true, DateTime.now(),
          eventName: evt));
    });

    if (_ack) {
      _socket?.emitWithAck(evt, payload, ack: (data) {
        if (mounted) {
          setState(() {
            _messages.add(SocketMessage(
                '${t['ack_received'] ?? 'Ack received'}: $data',
                false,
                DateTime.now(),
                eventName: evt));
          });
          _scrollToBottom();
        }
      });
    } else {
      _socket?.emit(evt, payload);
    }

    _scrollToBottom();
  }

  void _scrollToBottom() {
    Future.delayed(const Duration(milliseconds: 100), () {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  void _showSaveDialog(BuildContext context, var request) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return SaveRequestDialog(request: request);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final request = ref.watch(requestProvider);
    final t = ref.watch(translationsProvider);

    return MultiSplitViewTheme(
      data: MultiSplitViewThemeData(
        dividerThickness: 1,
        dividerHandleBuffer: 10,
        dividerPainter: DividerPainters.background(
          color: Theme.of(context).dividerColor,
          highlightedColor: Theme.of(context).colorScheme.primary,
        ),
      ),
      child: MultiSplitView(
        axis: Axis.vertical,
        initialAreas: [Area(flex: 0.5), Area(flex: 0.5)],
        builder: (context, area) {
          if (area.index == 0) {
            return Container(
              decoration: BoxDecoration(
                color: Theme.of(context).cardTheme.color,
                borderRadius: BorderRadius.circular(8.0),
              ),
              padding: const EdgeInsets.fromLTRB(8.0, 4.0, 8.0, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildHeaderBar(context, request),
                  const SizedBox(height: 12),
                  _buildConnectionBar(),
                  const SizedBox(height: 16),
                  SizedBox(
                    height: 32,
                    child: TabBar(
                      controller: _tabController,
                      isScrollable: true,
                      indicatorColor: Theme.of(context).colorScheme.secondary,
                      labelColor:
                          Theme.of(context).textTheme.bodyMedium?.color!,
                      unselectedLabelColor: Colors.grey,
                      tabAlignment: TabAlignment.start,
                      labelStyle: const TextStyle(
                          fontSize: 12, fontWeight: FontWeight.normal),
                      dividerColor: Theme.of(context).dividerColor,
                      tabs: [
                        Tab(text: t['message'] ?? 'Message'),
                        Tab(text: t['events'] ?? 'Events'),
                        Tab(text: t['params'] ?? 'Params'),
                        Tab(text: t['headers'] ?? 'Headers'),
                        Tab(text: t['settings'] ?? 'Settings'),
                      ],
                    ),
                  ),
                  const Divider(height: 1),
                  Expanded(
                    child: TabBarView(
                      controller: _tabController,
                      physics: const NeverScrollableScrollPhysics(),
                      children: [
                        _buildMessageTab(),
                        _buildEventsTab(),
                        _buildParamsTab(),
                        _buildHeadersTab(),
                        _buildSettingsTab(),
                      ],
                    ),
                  ),
                ],
              ),
            );
          } else {
            return Container(
              decoration: BoxDecoration(
                color: Theme.of(context).cardTheme.color,
                borderRadius: BorderRadius.circular(8.0),
              ),
              padding: const EdgeInsets.fromLTRB(8.0, 0, 8.0, 20.0),
              child: _buildResponseArea(),
            );
          }
        },
      ),
    );
  }

  Widget _buildHeaderBar(BuildContext context, var request) {
    final t = ref.watch(translationsProvider);
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Expanded(
          child: LayoutBuilder(
            builder: (context, constraints) {
              final maxNameWidth = (constraints.maxWidth * 0.28)
                  .clamp(140.0, 320.0)
                  .toDouble();
              return Row(
                children: [
                  if (request.folderPath != null &&
                      request.folderPath!.isNotEmpty) ...[
                    const FaIcon(FontAwesomeIcons.networkWired,
                        size: 12, color: Colors.blue),
                    const SizedBox(width: 8),
                    Flexible(
                      child: Text(
                        request.folderPath!.join(' › '),
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        softWrap: false,
                        style:
                            const TextStyle(fontSize: 12, color: Colors.grey),
                      ),
                    ),
                    const SizedBox(width: 8),
                  ],
                  Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      PopupMenuButton<String>(
                        tooltip: t['select_protocol'] ?? 'Select Protocol',
                        position: PopupMenuPosition.under,
                        padding: EdgeInsets.zero,
                        color: Theme.of(context).colorScheme.surface,
                        constraints: const BoxConstraints(),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(4.0),
                          side: BorderSide(
                            color: Theme.of(context).dividerColor,
                            width: 1.0,
                          ),
                        ),
                        splashRadius: 16,
                        onSelected: (String value) {
                          ref
                              .read(requestProvider.notifier)
                              .updateProtocol(value);
                        },
                        itemBuilder: (context) => <String>[
                          'http',
                          'grpc',
                          'websocket',
                          'socket.io',
                          'mqtt',
                          'tcp',
                          'udp'
                        ].map((String value) {
                          return PopupMenuItem<String>(
                            value: value,
                            height: 32,
                            padding: const EdgeInsets.symmetric(horizontal: 16),
                            child: Row(
                              children: [
                                FaIcon(_getProtocolIcon(value),
                                    size: 14, color: _getProtocolColor(value)),
                                const SizedBox(width: 8),
                                Text(value.toUpperCase(),
                                    style: const TextStyle(fontSize: 12)),
                              ],
                            ),
                          );
                        }).toList(),
                        child: MouseRegion(
                          onEnter: (_) =>
                              setState(() => _isProtocolHovered = true),
                          onExit: (_) =>
                              setState(() => _isProtocolHovered = false),
                          cursor: SystemMouseCursors.click,
                          child: Container(
                            margin: const EdgeInsets.only(right: 8.0),
                            padding: const EdgeInsets.all(6.0),
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: _isProtocolHovered
                                  ? Colors.grey.withOpacity(0.2)
                                  : Colors.transparent,
                            ),
                            child: FaIcon(
                              _getProtocolIcon(request.protocol),
                              size: 14,
                              color: _getProtocolColor(request.protocol),
                            ),
                          ),
                        ),
                      ),
                      ConstrainedBox(
                        constraints: BoxConstraints(maxWidth: maxNameWidth),
                        child: TextField(
                          controller: TextEditingController(text: request.name)
                            ..selection = TextSelection.collapsed(
                                offset: request.name.length),
                          maxLines: 1,
                          onChanged: (val) => ref
                              .read(requestProvider.notifier)
                              .updateName(val),
                          style: const TextStyle(fontSize: 12),
                          decoration: InputDecoration(
                            hintText:
                                t['untitled_request'] ?? 'Untitled Request',
                            filled: true,
                            fillColor: Theme.of(context).colorScheme.surface,
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(4.0),
                              borderSide: BorderSide(
                                  color: Colors.grey.withOpacity(0.5),
                                  width: 1.0),
                            ),
                            enabledBorder: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(4.0),
                              borderSide: BorderSide(
                                  color: Colors.grey.withOpacity(0.5),
                                  width: 1.0),
                            ),
                            focusedBorder: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(4.0),
                              borderSide: BorderSide(
                                  color: Colors.grey.withOpacity(0.5),
                                  width: 1.0),
                            ),
                            isDense: true,
                            contentPadding:
                                const EdgeInsets.fromLTRB(8, 7, 8, 7),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              );
            },
          ),
        ),
        SizedBox(
          height: 28,
          child: OutlinedButton.icon(
            onPressed: () => _showSaveDialog(context, request),
            icon: const FaIcon(FontAwesomeIcons.floppyDisk, size: 14),
            label:
                Text(t['save'] ?? 'Save', style: const TextStyle(fontSize: 12)),
            style: OutlinedButton.styleFrom(
              foregroundColor: Theme.of(context).textTheme.bodyMedium!.color,
              side: BorderSide(color: Theme.of(context).dividerColor),
              padding: const EdgeInsets.symmetric(horizontal: 12),
            ),
          ),
        ),
      ],
    );
  }

  IconData _getProtocolIcon(String protocol) {
    switch (protocol.toLowerCase()) {
      case 'grpc':
        return FontAwesomeIcons.server;
      case 'websocket':
      case 'ws':
        return FontAwesomeIcons.plug;
      case 'socket.io':
      case 'socket':
        return FontAwesomeIcons.circleNodes;
      case 'mqtt':
        return FontAwesomeIcons.satelliteDish;
      case 'tcp':
        return FontAwesomeIcons.networkWired;
      case 'udp':
        return FontAwesomeIcons.broadcastTower;
      case 'http':
      default:
        return FontAwesomeIcons.globe;
    }
  }

  Color _getProtocolColor(String protocol) {
    switch (protocol.toLowerCase()) {
      case 'grpc':
        return const Color(0xFF2196F3);
      case 'websocket':
      case 'ws':
        return const Color(0xFF9C27B0);
      case 'socket.io':
      case 'socket':
        return const Color(0xFFE91E63);
      case 'mqtt':
        return const Color(0xFFFF9800);
      case 'tcp':
        return const Color(0xFF009688);
      case 'udp':
        return const Color(0xFF3F51B5);
      case 'http':
      default:
        return const Color(0xFF0CBD7D);
    }
  }

  Widget _buildConnectionBar() {
    final t = ref.watch(translationsProvider);
    return Row(
      children: [
        Expanded(
          child: Container(
            height: _compactTableRowHeight,
            decoration: BoxDecoration(
              color: Colors.transparent,
              borderRadius: BorderRadius.circular(8.0),
              border: Border.all(
                  color: _urlFocusNode.hasFocus
                      ? Theme.of(context).colorScheme.primary
                      : Theme.of(context).dividerColor),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12),
                  child: Text(
                    'SOCKET',
                    style: TextStyle(
                      color: Color(0xFFE91E63),
                      fontWeight: FontWeight.bold,
                      fontSize: 12,
                    ),
                  ),
                ),
                const VerticalDivider(width: 1, thickness: 1),
                Expanded(
                  child: TextField(
                    controller: _urlController,
                    focusNode: _urlFocusNode,
                    style:
                        const TextStyle(fontFamily: 'Consolas', fontSize: 12),
                    decoration: InputDecoration(
                      hintText: t['enter_url'] ?? 'Enter URL',
                      hintStyle:
                          const TextStyle(color: Colors.grey, fontSize: 12),
                      border: InputBorder.none,
                      enabledBorder: InputBorder.none,
                      focusedBorder: InputBorder.none,
                      isDense: true,
                      contentPadding: const EdgeInsets.symmetric(
                          horizontal: 12, vertical: 6),
                    ),
                    onChanged: (val) {
                      ref.read(requestProvider.notifier).updateUrl(val);
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(width: 8),
        SizedBox(
          height: _compactTableRowHeight,
          child: ElevatedButton(
            onPressed:
                _urlController.text.isNotEmpty ? _toggleConnection : null,
            style: ElevatedButton.styleFrom(
              backgroundColor: _isConnected
                  ? Colors.red
                  : Theme.of(context).colorScheme.secondary,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0)),
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 0),
              elevation: 0,
            ),
            child: Row(
              children: [
                Text(
                  _isConnected
                      ? (t['disconnect'] ?? 'Disconnect')
                      : (t['connect'] ?? 'Connect'),
                  style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.normal,
                      fontSize: 12),
                ),
                if (!_isConnected) ...[
                  const SizedBox(width: 8),
                  const FaIcon(FontAwesomeIcons.bolt,
                      size: 12, color: Colors.white),
                ] else ...[
                  const SizedBox(width: 8),
                  const FaIcon(FontAwesomeIcons.xmark,
                      size: 12, color: Colors.white),
                ],
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildMessageTab() {
    final t = ref.watch(translationsProvider);
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Left Args List
        Container(
          width: 120,
          decoration: BoxDecoration(
            border: Border(
                right: BorderSide(color: Theme.of(context).dividerColor)),
          ),
          child: Column(
            children: [
              Expanded(
                child: ListView.builder(
                    itemCount: _args.length,
                    itemBuilder: (context, index) {
                      final arg = _args[index];
                      final isSelected = index == _selectedArgIndex;
                      return InkWell(
                        onTap: () => setState(() => _selectedArgIndex = index),
                        child: Container(
                          padding: const EdgeInsets.symmetric(
                              vertical: 8, horizontal: 12),
                          color: isSelected
                              ? Theme.of(context)
                                  .colorScheme
                                  .primary
                                  .withOpacity(0.1)
                              : null,
                          child: Text(arg['name'],
                              style: TextStyle(
                                  fontSize: 12,
                                  fontWeight: isSelected
                                      ? FontWeight.bold
                                      : FontWeight.normal)),
                        ),
                      );
                    }),
              ),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: OutlinedButton.icon(
                  onPressed: () {
                    setState(() {
                      _args.add({
                        'id': DateTime.now().millisecondsSinceEpoch.toString(),
                        'name': 'Arg ${_args.length + 1}',
                        'content': ''
                      });
                      _selectedArgIndex = _args.length - 1;
                    });
                    _saveSettings();
                  },
                  icon: const Icon(Icons.add, size: 14),
                  label: Text(t['arg'] ?? 'Arg',
                      style: const TextStyle(fontSize: 12)),
                  style: OutlinedButton.styleFrom(
                    minimumSize: const Size(double.infinity, 32),
                    padding: EdgeInsets.zero,
                  ),
                ),
              )
            ],
          ),
        ),

        // Right Editor Area
        Expanded(
          child: Column(
            children: [
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: AppCodeEditor(
                          text: _args[_selectedArgIndex]['content'],
                          hint: t['compose_message'] ?? 'Compose message',
                          language: _argType == 'JSON' ? 'json' : 'text',
                          onChanged: (v) {
                            _args[_selectedArgIndex]['content'] = v;
                            _saveSettings();
                          },
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Divider(height: 1),
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                  children: [
                    PopupMenuButton<String>(
                      tooltip: 'Argument Type',
                      position: PopupMenuPosition.under,
                      padding: EdgeInsets.zero,
                      color: Theme.of(context).colorScheme.surface,
                      constraints: const BoxConstraints(minWidth: 80),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(4.0),
                        side: BorderSide(
                          color: Theme.of(context).dividerColor,
                          width: 1.0,
                        ),
                      ),
                      splashRadius: 16,
                      onSelected: (String value) {
                        setState(() {
                          _argType = value;
                        });
                        _saveSettings();
                      },
                      itemBuilder: (context) => <String>['Text', 'JSON']
                          .map((String value) {
                        return PopupMenuItem<String>(
                           value: value,
                           height: 32,
                           padding: const EdgeInsets.symmetric(horizontal: 16),
                           child: Row(
                             children: [
                               if (value == _argType)
                                 const Padding(
                                   padding: EdgeInsets.only(right: 8.0),
                                   child: FaIcon(FontAwesomeIcons.check,
                                       size: 12, color: Colors.grey),
                                 )
                               else
                                 const SizedBox(width: 20),
                               Text(
                                 value,
                                 style: const TextStyle(fontSize: 12),
                               ),
                             ],
                           ),
                         );
                      }).toList(),
                      child: Container(
                        width: 80,
                        height: 28,
                        padding: const EdgeInsets.symmetric(horizontal: 8),
                        decoration: BoxDecoration(
                          border:
                              Border.all(color: Theme.of(context).dividerColor),
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              _argType,
                              style: TextStyle(
                                color: Theme.of(context).textTheme.bodyMedium?.color,
                                fontSize: 12,
                              ),
                            ),
                            const FaIcon(FontAwesomeIcons.chevronDown,
                                size: 10, color: Colors.grey),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Row(
                      children: [
                        SizedBox(
                          width: 24,
                          height: 24,
                          child: CustomCheckbox(
                            value: _ack,
                            onChanged: (v) {
                              setState(() => _ack = v ?? false);
                              _saveSettings();
                            },
                          ),
                        ),
                        const SizedBox(width: 4),
                        Text(t['ack'] ?? 'Ack',
                            style: const TextStyle(fontSize: 12)),
                      ],
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: SizedBox(
                        height: 28,
                        child: TextField(
                          controller: _eventNameController,
                          style: const TextStyle(fontSize: 12),
                          onChanged: (_) => _saveSettings(),
                          decoration: InputDecoration(
                            hintText: t['event_name_default'] ??
                                'Event name, defaults to "message"',
                            hintStyle: const TextStyle(
                                color: Colors.grey, fontSize: 12),
                            border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(4)),
                            contentPadding:
                                const EdgeInsets.symmetric(horizontal: 8),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    SizedBox(
                      height: 28,
                      child: ElevatedButton(
                        onPressed: _isConnected ? _sendMessage : null,
                        style: ElevatedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                        ),
                        child: Text(t['send'] ?? 'Send',
                            style: const TextStyle(fontSize: 12)),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildResponseArea() {
    final t = ref.watch(translationsProvider);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Text(t['response'] ?? 'Response',
              style:
                  const TextStyle(fontWeight: FontWeight.bold, fontSize: 12)),
        ),
        Expanded(
          child: _messages.isEmpty
              ? Center(
                  child: Text(
                      t['connect_to_send'] ??
                          'Connect to send and receive messages',
                      style: const TextStyle(color: Colors.grey, fontSize: 12)))
              : ListView.builder(
                  controller: _scrollController,
                  itemCount: _messages.length,
                  itemBuilder: (context, index) {
                    final msg = _messages[index];
                    return Padding(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 4),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Icon(
                              msg.isSent
                                  ? Icons.arrow_upward
                                  : Icons.arrow_downward,
                              size: 14,
                              color: msg.isSent ? Colors.blue : Colors.green),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                if (msg.eventName != null)
                                  Text('Event: ${msg.eventName}',
                                      style: const TextStyle(
                                          fontSize: 10, color: Colors.grey)),
                                Text(msg.content,
                                    style: const TextStyle(
                                        fontFamily: 'Consolas', fontSize: 12)),
                              ],
                            ),
                          ),
                        ],
                      ),
                    );
                  }),
        ),
      ],
    );
  }

  Widget _buildEventsTab() {
    final t = ref.watch(translationsProvider);
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          Row(
            children: [
              Expanded(
                  flex: 2,
                  child: Text('${t['events'] ?? 'Events'} +',
                      style: const TextStyle(
                          fontWeight: FontWeight.bold, fontSize: 12))),
              Expanded(
                  flex: 1,
                  child: Text(t['listen'] ?? 'Listen',
                      style: const TextStyle(
                          fontWeight: FontWeight.bold, fontSize: 12))),
              Expanded(
                  flex: 3,
                  child: Text(t['description'] ?? 'Description',
                      style: const TextStyle(
                          fontWeight: FontWeight.bold, fontSize: 12))),
            ],
          ),
          const Divider(),
          Expanded(
            child: ListView.builder(
                itemCount: _events.length + 1,
                itemBuilder: (context, index) {
                  if (index == _events.length) {
                    return Row(
                      children: [
                        Expanded(
                          flex: 2,
                          child: TextField(
                            style: TextStyle(
                              color: Theme.of(context).textTheme.bodyMedium?.color,
                              fontSize: 12,
                              fontFamily: 'Consolas',
                            ),
                            decoration: InputDecoration(
                              hintText: t['add_event'] ?? 'Add event',
                              hintStyle: const TextStyle(color: Colors.grey, fontSize: 12),
                              border: InputBorder.none,
                              enabledBorder: InputBorder.none,
                              focusedBorder: Theme.of(context).brightness == Brightness.dark
                                  ? OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(4.0),
                                      borderSide:
                                          const BorderSide(color: Colors.grey, width: 1.0),
                                    )
                                  : InputBorder.none,
                              isDense: true,
                              contentPadding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
                            ),
                            onSubmitted: (v) {
                              if (v.isNotEmpty) {
                                setState(() => _events.add({
                                      'name': v,
                                      'listen': true,
                                      'description': ''
                                    }));
                                _saveSettings();
                              }
                            },
                          ),
                        ),
                        Expanded(
                          flex: 1,
                          child: SizedBox(
                            height: 24,
                            child: Transform.scale(
                              scale: 0.65,
                              child: Switch(
                                value: false,
                                onChanged: null,
                                activeThumbColor: Theme.of(context).colorScheme.primary,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          flex: 3,
                          child: TextField(
                            style: TextStyle(
                              color: Theme.of(context).textTheme.bodyMedium?.color,
                              fontSize: 12,
                              fontFamily: 'Consolas',
                            ),
                            decoration: InputDecoration(
                              hintText: t['add_description'] ?? 'Add description',
                              hintStyle: const TextStyle(color: Colors.grey, fontSize: 12),
                              border: InputBorder.none,
                              enabledBorder: InputBorder.none,
                              focusedBorder: Theme.of(context).brightness == Brightness.dark
                                  ? OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(4.0),
                                      borderSide:
                                          const BorderSide(color: Colors.grey, width: 1.0),
                                    )
                                  : InputBorder.none,
                              isDense: true,
                              contentPadding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
                            ),
                            enabled: false,
                          ),
                        ),
                      ],
                    );
                  }
                  final ev = _events[index];
                  return Row(
                    children: [
                      Expanded(
                        flex: 2,
                        child: TextField(
                          controller: TextEditingController(text: ev['name'])
                            ..selection = TextSelection.collapsed(
                                offset: ev['name'].length),
                          style: TextStyle(
                            color: Theme.of(context).textTheme.bodyMedium?.color,
                            fontSize: 12,
                            fontFamily: 'Consolas',
                          ),
                          decoration: InputDecoration(
                            border: InputBorder.none,
                            enabledBorder: InputBorder.none,
                            focusedBorder: Theme.of(context).brightness == Brightness.dark
                                ? OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(4.0),
                                    borderSide:
                                        const BorderSide(color: Colors.grey, width: 1.0),
                                  )
                                : InputBorder.none,
                            isDense: true,
                            contentPadding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
                          ),
                          onChanged: (v) {
                            ev['name'] = v;
                            _saveSettings();
                          },
                        ),
                      ),
                      Expanded(
                        flex: 1,
                        child: SizedBox(
                          height: 24,
                          child: Transform.scale(
                            scale: 0.65,
                            child: Switch(
                              value: ev['listen'],
                              onChanged: (v) {
                                setState(() => ev['listen'] = v);
                                _saveSettings();
                              },
                              activeThumbColor: Theme.of(context).colorScheme.primary,
                            ),
                          ),
                        ),
                      ),
                      Expanded(
                        flex: 3,
                        child: TextField(
                          controller:
                              TextEditingController(text: ev['description'])
                                ..selection = TextSelection.collapsed(
                                    offset: ev['description'].length),
                          style: TextStyle(
                            color: Theme.of(context).textTheme.bodyMedium?.color,
                            fontSize: 12,
                            fontFamily: 'Consolas',
                          ),
                          decoration: InputDecoration(
                            border: InputBorder.none,
                            enabledBorder: InputBorder.none,
                            focusedBorder: Theme.of(context).brightness == Brightness.dark
                                ? OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(4.0),
                                    borderSide:
                                        const BorderSide(color: Colors.grey, width: 1.0),
                                  )
                                : InputBorder.none,
                            isDense: true,
                            contentPadding: const EdgeInsets.symmetric(horizontal: 4, vertical: 4),
                          ),
                          onChanged: (v) {
                            ev['description'] = v;
                            _saveSettings();
                          },
                        ),
                      ),
                    ],
                  );
                }),
          ),
        ],
      ),
    );
  }

  Widget _buildParamsTab() {
    final t = ref.watch(translationsProvider);
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.only(top: _compactSectionTopSpacing),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(t['query_parameters'] ?? 'Query Parameters',
                style: const TextStyle(
                    color: Colors.grey,
                    fontSize: 12,
                    fontWeight: FontWeight.normal)),
            const SizedBox(height: _compactSectionLabelGap),
            SharedDynamicTable(
              items: _params,
              onAdd: (key, value, desc) {
                setState(() => _params.add({
                      'key': key,
                      'value': value,
                      'description': desc,
                      'enabled': 'true'
                    }));
                ref.read(requestProvider.notifier).updateParams(_params);
              },
              onUpdate: (i, key, value) {
                _params[i]['key'] = key;
                _params[i]['value'] = value;
                ref.read(requestProvider.notifier).updateParams(_params);
              },
              onUpdateDesc: (i, desc) {
                _params[i]['description'] = desc;
                ref.read(requestProvider.notifier).updateParams(_params);
              },
              onRemove: (i) {
                setState(() => _params.removeAt(i));
                ref.read(requestProvider.notifier).updateParams(_params);
              },
              onToggle: (i, enabled) {
                _params[i]['enabled'] = enabled ? 'true' : 'false';
                ref.read(requestProvider.notifier).updateParams(_params);
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeadersTab() {
    final t = ref.watch(translationsProvider);
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.only(top: _compactSectionTopSpacing),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(t['headers'] ?? 'Headers',
                    style: const TextStyle(
                        color: Colors.grey,
                        fontSize: 12,
                        fontWeight: FontWeight.normal)),
                const Spacer(),
                TextButton(
                  onPressed: () {
                    setState(() =>
                        _hideAutoGeneratedHeaders = !_hideAutoGeneratedHeaders);
                  },
                  style: TextButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 8),
                    minimumSize: const Size(0, 28),
                  ),
                  child: Text(
                    _hideAutoGeneratedHeaders
                        ? (t['show_auto_headers'] ??
                            'Show auto-generated headers')
                        : (t['hide_auto_headers'] ??
                            'Hide auto-generated headers'),
                    style: const TextStyle(color: Colors.grey, fontSize: 12),
                  ),
                ),
              ],
            ),
            const SizedBox(height: _compactSectionLabelGap),
            SharedDynamicTable(
              items: _headers,
              mockItems: !_hideAutoGeneratedHeaders ? [
                {'key': 'Host', 'value': '<calculated at runtime>'},
              ] : null,
              onAdd: (key, value, desc) {
                setState(() => _headers.add({
                      'key': key,
                      'value': value,
                      'description': desc,
                      'enabled': 'true'
                    }));
                ref.read(requestProvider.notifier).updateHeaders(_headers);
              },
              onUpdate: (i, key, value) {
                _headers[i]['key'] = key;
                _headers[i]['value'] = value;
                ref.read(requestProvider.notifier).updateHeaders(_headers);
              },
              onUpdateDesc: (i, desc) {
                _headers[i]['description'] = desc;
                ref.read(requestProvider.notifier).updateHeaders(_headers);
              },
              onRemove: (i) {
                setState(() => _headers.removeAt(i));
                ref.read(requestProvider.notifier).updateHeaders(_headers);
              },
              onToggle: (i, enabled) {
                _headers[i]['enabled'] = enabled ? 'true' : 'false';
                ref.read(requestProvider.notifier).updateHeaders(_headers);
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSettingsTab() {
    final t = ref.watch(translationsProvider);
    return ListView(
      padding: const EdgeInsets.only(top: 16.0),
      children: [
        _buildSettingRow(
          t['enable_cert_verification'] ??
              'Enable server certificate verification',
          t['cert_verification_desc'] ??
              'Verify server certificate when connecting over a secure connection.',
          SizedBox(
            height: 24,
            child: Transform.scale(
              scale: 0.65,
              child: Switch(
                value: _verifyCertificate,
                onChanged: (v) {
                  setState(() => _verifyCertificate = v);
                  _saveSettings();
                },
                activeThumbColor: Theme.of(context).colorScheme.primary,
              ),
            ),
          ),
        ),
        _buildSettingRow(
          t['client_version'] ?? 'Client version',
          t['client_version_desc'] ??
              'Choose client version that should be used for connecting with the server.',
          PopupMenuButton<String>(
            tooltip: 'Client Version',
            position: PopupMenuPosition.under,
            padding: EdgeInsets.zero,
            color: Theme.of(context).colorScheme.surface,
            constraints: const BoxConstraints(minWidth: 80),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(4.0),
              side: BorderSide(
                color: Theme.of(context).dividerColor,
                width: 1.0,
              ),
            ),
            splashRadius: 16,
            onSelected: (String value) {
              setState(() {
                _clientVersion = value;
              });
              _saveSettings();
            },
            itemBuilder: (context) => <String>['v2', 'v3', 'v4']
                .map((String value) {
              return PopupMenuItem<String>(
                 value: value,
                 height: 32,
                 padding: const EdgeInsets.symmetric(horizontal: 16),
                 child: Row(
                   children: [
                     if (value == _clientVersion)
                       const Padding(
                         padding: EdgeInsets.only(right: 8.0),
                         child: FaIcon(FontAwesomeIcons.check,
                             size: 12, color: Colors.grey),
                       )
                     else
                       const SizedBox(width: 20),
                     Text(
                       value,
                       style: const TextStyle(fontSize: 12),
                     ),
                   ],
                 ),
               );
            }).toList(),
            child: Container(
              width: 80,
              height: 32,
              padding: const EdgeInsets.symmetric(horizontal: 8),
              decoration: BoxDecoration(
                border: Border.all(color: Theme.of(context).dividerColor),
                borderRadius: BorderRadius.circular(4.0),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    _clientVersion,
                    style: TextStyle(
                      color: Theme.of(context).textTheme.bodyMedium?.color,
                      fontSize: 12,
                    ),
                  ),
                  const FaIcon(FontAwesomeIcons.chevronDown,
                      size: 10, color: Colors.grey),
                ],
              ),
            ),
          ),
        ),
        _buildSettingRow(
          t['handshake_path'] ?? 'Handshake path',
          t['handshake_path_desc'] ??
              'Set the server path that should be used during the handshake request.',
          SizedBox(
            width: 150,
            height: 32,
            child: TextField(
              controller: _handshakePathController,
              style: TextStyle(
                  color: Theme.of(context).textTheme.bodyMedium?.color,
                  fontSize: 12,
                  fontFamily: 'Consolas'),
              decoration: InputDecoration(
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(4.0),
                  borderSide: BorderSide(color: Theme.of(context).dividerColor),
                ),
                contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
              ),
              onChanged: (_) => _saveSettings(),
            ),
          ),
        ),
        _buildSettingRow(
          t['handshake_timeout'] ?? 'Handshake request timeout',
          t['handshake_timeout_desc'] ??
              'Set how long the handshake request should wait before timing out in milliseconds. To never time out, set to 0.',
          SizedBox(
            width: 80,
            height: 32,
            child: TextField(
              controller: _timeoutController,
              style: TextStyle(
                  color: Theme.of(context).textTheme.bodyMedium?.color,
                  fontSize: 12,
                  fontFamily: 'Consolas'),
              decoration: InputDecoration(
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(4.0),
                  borderSide: BorderSide(color: Theme.of(context).dividerColor),
                ),
                contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
              ),
              onChanged: (_) => _saveSettings(),
            ),
          ),
        ),
        _buildSettingRow(
          t['reconnection_attempts'] ?? 'Reconnection attempts',
          t['reconnection_attempts_desc'] ??
              'Maximum reconnection attempts when the connection closes abruptly.',
          SizedBox(
            width: 80,
            height: 32,
            child: TextField(
              controller: _reconnectAttemptsController,
              style: TextStyle(
                  color: Theme.of(context).textTheme.bodyMedium?.color,
                  fontSize: 12,
                  fontFamily: 'Consolas'),
              decoration: InputDecoration(
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(4.0),
                  borderSide: BorderSide(color: Theme.of(context).dividerColor),
                ),
                contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
              ),
              onChanged: (_) => _saveSettings(),
            ),
          ),
        ),
        _buildSettingRow(
          t['reconnection_intervals'] ?? 'Reconnection intervals',
          t['reconnection_intervals_desc'] ??
              'Interval between each reconnection attempt in milliseconds.',
          SizedBox(
            width: 80,
            height: 32,
            child: TextField(
              controller: _reconnectIntervalController,
              style: TextStyle(
                  color: Theme.of(context).textTheme.bodyMedium?.color,
                  fontSize: 12,
                  fontFamily: 'Consolas'),
              decoration: InputDecoration(
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(4.0),
                  borderSide: BorderSide(color: Theme.of(context).dividerColor),
                ),
                contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
              ),
              onChanged: (_) => _saveSettings(),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSettingRow(String title, String description, Widget control) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            flex: 3,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500)),
                const SizedBox(height: 4),
                Text(description,
                    style: const TextStyle(fontSize: 12, color: Colors.grey)),
              ],
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            flex: 2,
            child: Align(
              alignment: Alignment.centerLeft,
              child: control,
            ),
          ),
        ],
      ),
    );
  }
}
