import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:multi_split_view/multi_split_view.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'shared_dynamic_table.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
import 'dart:convert';

import '../providers/request_provider.dart';
import '../providers/settings_provider.dart';
import 'save_request_dialog.dart';
import 'app_code_editor.dart';
import 'package:post_lens/presentation/widgets/common/custom_controls.dart';

class WebSocketMessage {
  final String content;
  final bool isSent;
  final DateTime timestamp;
  final bool isSystem;

  WebSocketMessage(this.content, this.isSent, this.timestamp,
      {this.isSystem = false});
}

class WebSocketPane extends ConsumerStatefulWidget {
  const WebSocketPane({super.key});

  @override
  ConsumerState<WebSocketPane> createState() => _WebSocketPaneState();
}

class _WebSocketPaneState extends ConsumerState<WebSocketPane>
    with SingleTickerProviderStateMixin {
  static const double _compactTableRowHeight = 28;
  static const double _compactTableOuterHorizontalPadding = 6;
  static const double _compactTableCellHorizontalPadding = 4;
  static const double _compactTableColumnGap = 6;
  static const double _compactTableSideSlotWidth = 28;
  static const double _compactTableLeadingSlotWidth = 22;
  static const double _compactSectionTopSpacing = 12;
  static const double _compactSectionLabelGap = 6;

  final TextEditingController _urlController = TextEditingController();
  final FocusNode _urlFocusNode = FocusNode();
  final TextEditingController _messageController = TextEditingController();
  String _messageContent = '{\n  "a": "12312"\n}';
  final ScrollController _scrollController = ScrollController();
  late TabController _tabController;

  bool _isConnected = false;
  bool _isProtocolHovered = false;
  final List<WebSocketMessage> _messages = [];
  String _messageFormat = 'JSON';
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';

  WebSocketChannel? _channel;
  bool _showAutoGeneratedHeaders = false;

  String _messageFilter = 'All Messages'; // 'All Messages', 'Sent Messages', 'Received Messages'
  
  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 4, vsync: this);
    _urlFocusNode.addListener(() => setState(() {}));
    _searchController.addListener(() {
      setState(() {
        _searchQuery = _searchController.text.toLowerCase();
      });
    });
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final req = ref.read(requestProvider);
      if (req.url.isNotEmpty) {
        _urlController.text = req.url;
      }
    });
  }

  @override
  void dispose() {
    _channel?.sink.close();
    _urlController.dispose();
    _urlFocusNode.dispose();
    _messageController.dispose();
    _scrollController.dispose();
    _tabController.dispose();
    _searchController.dispose();
    super.dispose();
  }

  void _toggleConnection() {
    if (_isConnected) {
      _channel?.sink.close();
      setState(() {
        _isConnected = false;
        final t = ref.read(translationsProvider);
        _messages.add(WebSocketMessage(
            t['disconnected'] ?? 'Disconnected', false, DateTime.now(),
            isSystem: true));
      });
    } else {
      try {
        final url = _urlController.text;
        final req = ref.read(requestProvider);
        final headers = <String, dynamic>{};
        for (final h in req.headers) {
          if (h['enabled'] != 'false' &&
              h['key'] != null &&
              h['key']!.isNotEmpty) {
            headers[h['key']!] = h['value'] ?? '';
          }
        }

        _channel = WebSocketChannel.connect(Uri.parse(url));

        setState(() {
          _isConnected = true;
          final t = ref.read(translationsProvider);
          _messages.add(WebSocketMessage(
              '${t['connected_to'] ?? 'Connected to'} $url',
              false,
              DateTime.now(),
              isSystem: true));
        });

        _channel!.stream.listen(
          (message) {
            if (mounted) {
              setState(() {
                _messages.add(WebSocketMessage(
                    message.toString(), false, DateTime.now()));
              });
              _scrollToBottom();
            }
          },
          onError: (error) {
            if (mounted) {
              setState(() {
                final t = ref.read(translationsProvider);
                _messages.add(WebSocketMessage(
                    '${t['connect_error'] ?? 'Connect Error'}: $error',
                    false,
                    DateTime.now(),
                    isSystem: true));
                _isConnected = false;
              });
              _scrollToBottom();
            }
          },
          onDone: () {
            if (mounted) {
              setState(() {
                if (_isConnected) {
                  final t = ref.read(translationsProvider);
                  _messages.add(WebSocketMessage(
                      t['connection_closed_by_server'] ??
                          'Connection closed by server',
                      false,
                      DateTime.now(),
                      isSystem: true));
                  _isConnected = false;
                }
              });
              _scrollToBottom();
            }
          },
        );
      } catch (e) {
        setState(() {
          final t = ref.read(translationsProvider);
          _messages.add(WebSocketMessage(
              '${t['failed_to_connect'] ?? 'Failed to connect'}: $e',
              false,
              DateTime.now(),
              isSystem: true));
        });
      }
    }
    _scrollToBottom();
  }

  void _sendMessage() {
    final text = _messageContent;
    if (text.isEmpty || !_isConnected) return;

    setState(() {
      _messages.add(WebSocketMessage(text, true, DateTime.now()));
      // no clear
      _channel?.sink.add(text);
    });
    _scrollToBottom();
  }

  void _scrollToBottom() {
    Future.delayed(const Duration(milliseconds: 100), () {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  void _showSaveDialog(BuildContext context, var request) {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return SaveRequestDialog(request: request);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final request = ref.watch(requestProvider);

    return MultiSplitViewTheme(
      data: MultiSplitViewThemeData(
        dividerThickness: 1,
        dividerHandleBuffer: 10,
        dividerPainter: DividerPainters.background(
          color: Theme.of(context).dividerColor,
          highlightedColor: Theme.of(context).colorScheme.primary,
        ),
      ),
      child: MultiSplitView(
        axis: Axis.vertical,
        initialAreas: [Area(flex: 0.5), Area(flex: 0.5)],
        builder: (context, area) {
          if (area.index == 0) {
            return Container(
              decoration: BoxDecoration(
                color: Theme.of(context).cardTheme.color,
                borderRadius: BorderRadius.circular(8.0),
              ),
              padding: const EdgeInsets.fromLTRB(8.0, 4.0, 8.0, 0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildHeaderBar(context, request),
                  const SizedBox(height: 12),
                  _buildConnectionBar(),
                  const SizedBox(height: 16),
                  _buildTabBar(),
                  Expanded(
                    child: TabBarView(
                      controller: _tabController,
                      children: [
                        _buildMessageTab(),
                        _buildParamsTab(),
                        _buildHeadersTab(),
                        _buildSettingsTab(),
                      ],
                    ),
                  ),
                ],
              ),
            );
          } else {
            return Container(
              decoration: BoxDecoration(
                color: Theme.of(context).cardTheme.color,
                borderRadius: BorderRadius.circular(8.0),
              ),
              padding: const EdgeInsets.fromLTRB(8.0, 0, 8.0, 20.0),
              child: _buildResponseArea(),
            );
          }
        },
      ),
    );
  }

  Widget _buildHeaderBar(BuildContext context, var request) {
    final t = ref.watch(translationsProvider);
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Expanded(
          child: Row(
            children: [
              if (request.folderPath != null &&
                  request.folderPath!.isNotEmpty) ...[
                const FaIcon(FontAwesomeIcons.networkWired,
                    size: 12, color: Colors.blue),
                const SizedBox(width: 8),
                for (int i = 0; i < request.folderPath!.length; i++) ...[
                  Text(
                    request.folderPath![i],
                    style: const TextStyle(fontSize: 12, color: Colors.grey),
                  ),
                  const Padding(
                    padding: EdgeInsets.symmetric(horizontal: 4.0),
                    child:
                        Icon(Icons.chevron_right, size: 12, color: Colors.grey),
                  ),
                ],
              ],
              Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  PopupMenuButton<String>(
                    tooltip: 'Select Protocol',
                    position: PopupMenuPosition.under,
                    padding: EdgeInsets.zero,
                    color: Theme.of(context).colorScheme.surface,
                    constraints: const BoxConstraints(),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4.0),
                      side: BorderSide(
                        color: Theme.of(context).dividerColor,
                        width: 1.0,
                      ),
                    ),
                    splashRadius: 16,
                    onSelected: (String value) {
                      ref.read(requestProvider.notifier).updateProtocol(value);
                    },
                    itemBuilder: (context) => <String>[
                      'http',
                                    'grpc',
                                    'websocket',
                                    'socket.io',
                                    'mqtt',
                                    'tcp',
                                    'udp'
                    ].map((String value) {
                      return PopupMenuItem<String>(
                        value: value,
                        height: 32,
                        padding: const EdgeInsets.symmetric(horizontal: 16),
                        child: Row(
                          children: [
                            FaIcon(_getProtocolIcon(value),
                                size: 14, color: _getProtocolColor(value)),
                            const SizedBox(width: 8),
                            Text(value.toUpperCase(),
                                style: const TextStyle(fontSize: 12)),
                          ],
                        ),
                      );
                    }).toList(),
                    child: MouseRegion(
                      onEnter: (_) => setState(() => _isProtocolHovered = true),
                      onExit: (_) => setState(() => _isProtocolHovered = false),
                      cursor: SystemMouseCursors.click,
                      child: Container(
                        margin: const EdgeInsets.only(right: 8.0),
                        padding: const EdgeInsets.all(6.0),
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: _isProtocolHovered
                              ? Colors.grey.withOpacity(0.2)
                              : Colors.transparent,
                        ),
                        child: FaIcon(
                          _getProtocolIcon(request.protocol),
                          size: 14,
                          color: _getProtocolColor(request.protocol),
                        ),
                      ),
                    ),
                  ),
                  IntrinsicWidth(
                    child: TextField(
                      controller: TextEditingController(text: request.name)
                        ..selection = TextSelection.collapsed(
                            offset: request.name.length),
                      onChanged: (val) =>
                          ref.read(requestProvider.notifier).updateName(val),
                      style: TextStyle(
                          color: Theme.of(context).textTheme.bodyMedium?.color,
                          fontSize: 12),
                      decoration: InputDecoration(
                        hintText: t['untitled_request'] ?? 'Untitled Request',
                        filled: true,
                        fillColor: Theme.of(context).colorScheme.surface,
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(4.0),
                          borderSide: BorderSide(
                              color: Colors.grey.withOpacity(0.5), width: 1.0),
                        ),
                        enabledBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(4.0),
                          borderSide: BorderSide(
                              color: Colors.grey.withOpacity(0.5), width: 1.0),
                        ),
                        focusedBorder: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(4.0),
                          borderSide: BorderSide(
                              color: Colors.grey.withOpacity(0.5), width: 1.0),
                        ),
                        isDense: true,
                        contentPadding: const EdgeInsets.fromLTRB(8, 7, 8, 7),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
        SizedBox(
          height: 28,
          child: OutlinedButton.icon(
            onPressed: () => _showSaveDialog(context, request),
            icon: const FaIcon(FontAwesomeIcons.floppyDisk, size: 14),
            label:
                Text(t['save'] ?? 'Save', style: const TextStyle(fontSize: 12)),
            style: OutlinedButton.styleFrom(
              foregroundColor: Theme.of(context).textTheme.bodyMedium!.color,
              side: BorderSide(color: Theme.of(context).dividerColor),
              padding: const EdgeInsets.symmetric(horizontal: 12),
            ),
          ),
        ),
      ],
    );
  }

  IconData _getProtocolIcon(String protocol) {
    switch (protocol.toLowerCase()) {
      case 'grpc':
        return FontAwesomeIcons.server;
      case 'websocket':
      case 'ws':
        return FontAwesomeIcons.plug;
      case 'socket.io':
      case 'socket':
        return FontAwesomeIcons.circleNodes;
      case 'mqtt':
        return FontAwesomeIcons.satelliteDish;
      case 'tcp':
        return FontAwesomeIcons.networkWired;
      case 'udp':
        return FontAwesomeIcons.broadcastTower;
      case 'http':
      default:
        return FontAwesomeIcons.globe;
    }
  }

  Color _getProtocolColor(String protocol) {
    switch (protocol.toLowerCase()) {
      case 'grpc':
        return const Color(0xFF2196F3);
      case 'websocket':
      case 'ws':
        return const Color(0xFF9C27B0);
      case 'socket.io':
      case 'socket':
        return const Color(0xFFE91E63);
      case 'mqtt':
        return const Color(0xFFFF9800);
      case 'tcp':
        return const Color(0xFF009688);
      case 'udp':
        return const Color(0xFF3F51B5);
      case 'http':
      default:
        return const Color(0xFF0CBD7D);
    }
  }

  Widget _buildConnectionBar() {
    final t = ref.watch(translationsProvider);
    return Row(
      children: [
        Expanded(
          child: Container(
            height: _compactTableRowHeight,
            decoration: BoxDecoration(
              color: Colors.transparent,
              borderRadius: BorderRadius.circular(8.0),
              border: Border.all(
                  color: _urlFocusNode.hasFocus
                      ? Theme.of(context).colorScheme.primary
                      : Theme.of(context).dividerColor),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12),
                  child: Text(
                    t['ws'] ?? 'WS',
                    style: TextStyle(
                      color: Color(0xFF9C27B0),
                      fontWeight: FontWeight.bold,
                      fontSize: 12,
                    ),
                  ),
                ),
                const VerticalDivider(width: 1, thickness: 1),
                Expanded(
                  child: TextField(
                    controller: _urlController,
                    focusNode: _urlFocusNode,
                    style: TextStyle(
                        color: Theme.of(context).textTheme.bodyMedium?.color,
                        fontFamily: 'Consolas',
                        fontSize: 12),
                    decoration: const InputDecoration(
                      hintText: 'ws://localhost:8080',
                      hintStyle: TextStyle(color: Colors.grey, fontSize: 12),
                      border: InputBorder.none,
                      enabledBorder: InputBorder.none,
                      focusedBorder: InputBorder.none,
                      isDense: true,
                      contentPadding:
                          EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                    ),
                    onChanged: (val) {
                      ref.read(requestProvider.notifier).updateUrl(val);
                    },
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(width: 8),
        SizedBox(
          height: _compactTableRowHeight,
          child: ElevatedButton(
            onPressed:
                _urlController.text.isNotEmpty ? _toggleConnection : null,
            style: ElevatedButton.styleFrom(
              backgroundColor: _isConnected
                  ? Colors.red
                  : Theme.of(context).colorScheme.secondary,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0)),
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 0),
              elevation: 0,
            ),
            child: Row(
              children: [
                Text(
                  _isConnected
                      ? (t['disconnect'] ?? 'Disconnect')
                      : (t['connect'] ?? 'Connect'),
                  style: const TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.normal,
                      fontSize: 12),
                ),
                if (!_isConnected) ...[
                  const SizedBox(width: 8),
                  const FaIcon(FontAwesomeIcons.plug,
                      size: 12, color: Colors.white),
                ] else ...[
                  const SizedBox(width: 8),
                  const FaIcon(FontAwesomeIcons.plugCircleXmark,
                      size: 12, color: Colors.white),
                ]
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildTabBar() {
    final t = ref.watch(translationsProvider);
    return SizedBox(
      height: 32,
      child: TabBar(
        controller: _tabController,
        isScrollable: true,
        indicatorColor: Theme.of(context).colorScheme.secondary,
        labelColor: Theme.of(context).textTheme.bodyMedium?.color!,
        unselectedLabelColor: Colors.grey,
        tabAlignment: TabAlignment.start,
        labelStyle:
            const TextStyle(fontSize: 12, fontWeight: FontWeight.normal),
        dividerColor: Theme.of(context).dividerColor,
        tabs: [
          Tab(text: t['message'] ?? 'Message'),
          Tab(text: t['params'] ?? 'Params'),
          Tab(text: t['headers'] ?? 'Headers'),
          Tab(text: t['settings'] ?? 'Settings'),
        ],
      ),
    );
  }

  Widget _buildMessageTab() {
    final t = ref.watch(translationsProvider);

    return Column(
      children: [
        Expanded(
          flex: 1,
          child: Padding(
            padding: const EdgeInsets.only(top: 16.0),
            child: AppCodeEditor(
              text: _messageContent,
              hint: t['enter_message_here'] ?? 'Enter message here',
              language:
                  _messageFormat.toLowerCase() == 'json' ? 'json' : 'text',
              onChanged: (val) {
                _messageContent = val;
              },
            ),
          ),
        ),
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 16.0),
          child: Row(
            children: [
              PopupMenuButton<String>(
                tooltip: 'Message Format',
                position: PopupMenuPosition.under,
                padding: EdgeInsets.zero,
                color: Theme.of(context).colorScheme.surface,
                constraints: const BoxConstraints(minWidth: 90),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4.0),
                  side: BorderSide(
                    color: Theme.of(context).dividerColor,
                    width: 1.0,
                  ),
                ),
                splashRadius: 16,
                onSelected: (String value) {
                  setState(() {
                    _messageFormat = value;
                  });
                },
                itemBuilder: (context) =>
                    <String>['Text', 'JSON', 'XML', 'HTML', 'Binary']
                        .map((String value) {
                  return PopupMenuItem<String>(
                     value: value,
                     height: 32,
                     padding: const EdgeInsets.symmetric(horizontal: 16),
                     child: Row(
                       children: [
                         if (value == _messageFormat)
                           const Padding(
                             padding: EdgeInsets.only(right: 8.0),
                             child: FaIcon(FontAwesomeIcons.check,
                                 size: 12, color: Colors.grey),
                           )
                         else
                           const SizedBox(width: 20),
                         Text(
                           value,
                           style: const TextStyle(fontSize: 12),
                         ),
                       ],
                     ),
                   );
                }).toList(),
                child: Container(
                  width: 90,
                  height: 32,
                  decoration: BoxDecoration(
                    border: Border.all(color: Theme.of(context).dividerColor),
                    borderRadius: BorderRadius.circular(4.0),
                  ),
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        _messageFormat,
                        style: TextStyle(
                          color: Theme.of(context).textTheme.bodyMedium?.color,
                          fontSize: 12,
                        ),
                      ),
                      const FaIcon(FontAwesomeIcons.chevronDown,
                          size: 10, color: Colors.grey),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: 8),
              IconButton(
                icon: const Icon(Icons.format_align_left, size: 18),
                onPressed: () {},
                tooltip: t['format'] ?? 'Format',
              ),
              const Spacer(),
              SizedBox(
                height: 32,
                child: ElevatedButton(
                  onPressed: _isConnected ? _sendMessage : null,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(4.0)),
                  ),
                  child: Text(t['send'] ?? 'Send'),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildResponseArea() {
    final t = ref.watch(translationsProvider);
    final filteredMessages = _messages.where((msg) {
      bool matchesSearch = msg.content.toLowerCase().contains(_searchQuery);
      bool matchesFilter = true;
      if (_messageFilter == 'Sent Messages') {
        matchesFilter = msg.isSent && !msg.isSystem;
      } else if (_messageFilter == 'Received Messages') {
        matchesFilter = !msg.isSent && !msg.isSystem;
      }
      return matchesSearch && matchesFilter;
    }).toList();

    return Column(
      children: [
        Container(
          padding: const EdgeInsets.symmetric(vertical: 8.0),
          decoration: BoxDecoration(
            border: Border(
                bottom: BorderSide(color: Theme.of(context).dividerColor)),
          ),
          child: Row(
            children: [
              Text(t['response'] ?? 'Response',
                  style: const TextStyle(fontWeight: FontWeight.bold)),
              const Spacer(),
              if (_isConnected)
                Text(t['connected'] ?? 'Connected',
                    style: const TextStyle(color: Colors.green, fontSize: 12)),
              const SizedBox(width: 8),
              const Icon(Icons.more_horiz, size: 18),
            ],
          ),
        ),
        Container(
          padding: const EdgeInsets.symmetric(vertical: 8.0),
          child: Row(
            children: [
              Expanded(
                child: SizedBox(
                  height: 32,
                  child: TextField(
                    controller: _searchController,
                    decoration: InputDecoration(
                      hintText: t['search'] ?? 'Search',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(4.0),
                        borderSide: BorderSide(color: Theme.of(context).dividerColor),
                      ),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(4.0),
                        borderSide: BorderSide(color: Theme.of(context).dividerColor),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(4.0),
                        borderSide: BorderSide(color: Theme.of(context).colorScheme.primary),
                      ),
                      contentPadding:
                          const EdgeInsets.symmetric(horizontal: 8, vertical: 12),
                      isDense: true,
                    ),
                    style: TextStyle(
                        color: Theme.of(context).textTheme.bodyMedium?.color,
                        fontSize: 12, 
                        height: 1.2),
                  ),
                ),
              ),
              const SizedBox(width: 8),
              PopupMenuButton<String>(
                initialValue: _messageFilter,
                color: Theme.of(context).colorScheme.surface,
                padding: EdgeInsets.zero,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(4.0),
                  side: BorderSide(
                    color: Theme.of(context).dividerColor,
                    width: 1.0,
                  ),
                ),
                onSelected: (String value) {
                  setState(() {
                    _messageFilter = value;
                  });
                },
                itemBuilder: (BuildContext context) => <PopupMenuEntry<String>>[
                  PopupMenuItem<String>(
                    value: 'All Messages',
                    height: 32,
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    child: Row(
                      children: [
                        if (_messageFilter == 'All Messages')
                          const Padding(
                            padding: EdgeInsets.only(right: 8.0),
                            child: FaIcon(FontAwesomeIcons.check,
                                size: 12, color: Colors.grey),
                          )
                        else
                          const SizedBox(width: 20),
                        Text(t['all_messages'] ?? 'All Messages', style: const TextStyle(fontSize: 12)),
                      ],
                    ),
                  ),
                  PopupMenuItem<String>(
                    value: 'Sent Messages',
                    height: 32,
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    child: Row(
                      children: [
                        if (_messageFilter == 'Sent Messages')
                          const Padding(
                            padding: EdgeInsets.only(right: 8.0),
                            child: FaIcon(FontAwesomeIcons.check,
                                size: 12, color: Colors.grey),
                          )
                        else
                          const SizedBox(width: 20),
                        Text(t['sent_messages'] ?? 'Sent Messages', style: const TextStyle(fontSize: 12)),
                      ],
                    ),
                  ),
                  PopupMenuItem<String>(
                    value: 'Received Messages',
                    height: 32,
                    padding: const EdgeInsets.symmetric(horizontal: 16),
                    child: Row(
                      children: [
                        if (_messageFilter == 'Received Messages')
                          const Padding(
                            padding: EdgeInsets.only(right: 8.0),
                            child: FaIcon(FontAwesomeIcons.check,
                                size: 12, color: Colors.grey),
                          )
                        else
                          const SizedBox(width: 20),
                        Text(t['received_messages'] ?? 'Received Messages', style: const TextStyle(fontSize: 12)),
                      ],
                    ),
                  ),
                ],
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        t[_messageFilter.toLowerCase().replaceAll(' ', '_')] ?? _messageFilter,
                        style: const TextStyle(color: Colors.grey, fontSize: 13),
                      ),
                      const SizedBox(width: 4),
                      const Icon(Icons.arrow_drop_down, color: Colors.grey, size: 16),
                    ],
                  ),
                ),
              ),
              TextButton.icon(
                onPressed: () {
                  setState(() => _messages.clear());
                },
                icon: const Icon(Icons.delete_outline,
                    size: 16, color: Colors.grey),
                label: Text(t['clear_messages'] ?? 'Clear Messages',
                    style: const TextStyle(color: Colors.grey, fontSize: 13)),
              ),
            ],
          ),
        ),
        Expanded(
          child: ListView.builder(
            controller: _scrollController,
            itemCount: filteredMessages.length,
            itemBuilder: (context, index) {
              final msg = filteredMessages[index];
              bool isHovered = false;
              return StatefulBuilder(
                builder: (context, setRowState) {
                  return MouseRegion(
                    onEnter: (_) => setRowState(() => isHovered = true),
                    onExit: (_) => setRowState(() => isHovered = false),
                    child: Container(
                      decoration: BoxDecoration(
                        color: isHovered ? Theme.of(context).hoverColor : null,
                        border: Border(
                            bottom:
                                BorderSide(color: Theme.of(context).dividerColor)),
                      ),
                      padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 4.0),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          if (isHovered)
                            Container(
                              width: 16,
                              height: 16,
                              margin: const EdgeInsets.only(right: 8, top: 2),
                              child: CustomCheckbox(
                                value: false,
                                onChanged: (val) {},
                                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                                splashRadius: 0,
                              ),
                            )
                          else
                            const SizedBox(width: 24),
                          if (msg.isSystem)
                            const Padding(
                              padding: EdgeInsets.only(top: 2.0),
                              child: Icon(Icons.check_circle_outline,
                                  color: Colors.green, size: 16),
                            )
                          else if (msg.isSent)
                            const Padding(
                              padding: EdgeInsets.only(top: 2.0),
                              child: Icon(Icons.arrow_upward,
                                  color: Colors.orange, size: 16),
                            )
                          else
                            const Padding(
                              padding: EdgeInsets.only(top: 2.0),
                              child: Icon(Icons.arrow_downward,
                                  color: Colors.blue, size: 16),
                            ),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              msg.content,
                              style: const TextStyle(
                                  fontFamily: 'Consolas', fontSize: 13),
                            ),
                          ),
                          if (isHovered) ...[
                            const SizedBox(width: 8),
                            InkWell(
                              onTap: () {
                                Clipboard.setData(ClipboardData(text: msg.content));
                                ScaffoldMessenger.of(context).showSnackBar(
                                  SnackBar(content: Text(t['copied_to_clipboard'] ?? 'Copied to clipboard')),
                                );
                              },
                              child: const Icon(Icons.copy, size: 16, color: Colors.grey),
                            ),
                            const SizedBox(width: 8),
                            InkWell(
                              onTap: () {
                                // Save functionality can be implemented later
                              },
                              child: const Icon(Icons.save_alt, size: 16, color: Colors.grey),
                            ),
                            const SizedBox(width: 8),
                            Tooltip(
                              richMessage: TextSpan(
                                children: [
                                  TextSpan(text: 'Size: ${utf8.encode(msg.content).length} B\n'),
                                  TextSpan(text: 'Time: ${msg.timestamp.hour.toString().padLeft(2, '0')}:${msg.timestamp.minute.toString().padLeft(2, '0')}:${msg.timestamp.second.toString().padLeft(2, '0')}.${msg.timestamp.millisecond.toString().padLeft(3, '0')}\n'),
                                  const TextSpan(text: 'MIME Type: text/plain'),
                                ],
                                style: const TextStyle(fontSize: 12, color: Colors.white),
                              ),
                              child: const Icon(Icons.info_outline, size: 16, color: Colors.grey),
                            ),
                          ],
                          const SizedBox(width: 8),
                          Text(
                            '${msg.timestamp.hour.toString().padLeft(2, '0')}:${msg.timestamp.minute.toString().padLeft(2, '0')}:${msg.timestamp.second.toString().padLeft(2, '0')}.${msg.timestamp.millisecond.toString().padLeft(3, '0')}',
                            style: const TextStyle(color: Colors.grey, fontSize: 12),
                          ),
                          const SizedBox(width: 8),
                          const Icon(Icons.keyboard_arrow_down,
                              color: Colors.grey, size: 16),
                        ],
                      ),
                    ),
                  );
                },
              );
            },
          ),
        ),
      ],
    );
  }

  Widget _buildParamsTab() {
    final t = ref.watch(translationsProvider);
    final req = ref.watch(requestProvider);
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.only(top: _compactSectionTopSpacing),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(t['query_parameters'] ?? 'Query Parameters',
                style: const TextStyle(
                    color: Colors.grey,
                    fontSize: 12,
                    fontWeight: FontWeight.normal)),
            const SizedBox(height: _compactSectionLabelGap),
            SharedDynamicTable(
              items: req.params,
              onAdd: (key, value, desc) =>
                  ref.read(requestProvider.notifier).addParam(key, value, desc),
              onUpdate: (i, key, value) =>
                  ref.read(requestProvider.notifier).updateParam(i, key, value),
              onRemove: (i) =>
                  ref.read(requestProvider.notifier).removeParam(i),
              onToggle: (i, enabled) => ref
                  .read(requestProvider.notifier)
                  .updateParamEnabled(i, enabled),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeadersTab() {
    final t = ref.watch(translationsProvider);
    final req = ref.watch(requestProvider);
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.only(top: _compactSectionTopSpacing),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Text(t['headers'] ?? 'Headers',
                    style: const TextStyle(
                        color: Colors.grey,
                        fontSize: 12,
                        fontWeight: FontWeight.normal)),
                const Spacer(),
                TextButton(
                  onPressed: () {
                    setState(() =>
                        _showAutoGeneratedHeaders = !_showAutoGeneratedHeaders);
                  },
                  style: TextButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 8),
                    minimumSize: const Size(0, 28),
                  ),
                  child: Text(
                    _showAutoGeneratedHeaders
                        ? (t['hide_auto_headers'] ??
                            'Hide auto-generated headers')
                        : (t['show_auto_headers'] ??
                            'Show auto-generated headers'),
                    style: const TextStyle(color: Colors.grey, fontSize: 12),
                  ),
                ),
              ],
            ),
            const SizedBox(height: _compactSectionLabelGap),
            SharedDynamicTable(
              items: req.headers,
              mockItems: !_showAutoGeneratedHeaders ? [
                {'key': 'Host', 'value': '<calculated at runtime>'},
                {'key': 'Connection', 'value': 'Upgrade'},
                {'key': 'Upgrade', 'value': 'websocket'},
                {'key': 'Sec-WebSocket-Key', 'value': '<calculated at runtime>'},
                {'key': 'Sec-WebSocket-Version', 'value': '13'},
                {'key': 'Sec-WebSocket-Extensions', 'value': 'permessage-deflate; client_max_window_bits'},
              ] : null,
              onAdd: (key, value, desc) =>
                  ref.read(requestProvider.notifier).addHeader(key, value, desc),
              onUpdate: (i, key, value) => ref
                  .read(requestProvider.notifier)
                  .updateHeader(i, key, value),
              onRemove: (i) =>
                  ref.read(requestProvider.notifier).removeHeader(i),
              onToggle: (i, enabled) => ref
                  .read(requestProvider.notifier)
                  .updateHeaderEnabled(i, enabled),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSettingsTab() {
    final t = ref.watch(translationsProvider);
    return ListView(
      padding: const EdgeInsets.only(top: 16.0),
      children: [
        _buildSettingRow(
          t['enable_cert_verification'] ??
              'Enable server certificate verification',
          t['cert_verification_desc'] ??
              'Verify server certificate when connecting over a secure connection.',
          SizedBox(
            height: 24,
            child: Transform.scale(
              scale: 0.65,
              child: Switch(
                value: false,
                onChanged: (v) {},
                activeThumbColor: Theme.of(context).colorScheme.primary,
              ),
            ),
          ),
        ),
        _buildSettingRow(
          t['handshake_timeout'] ?? 'Handshake request timeout',
          t['handshake_timeout_desc'] ??
              'Set how long the handshake request should wait before timing out in milliseconds. To never time out, set to 0.',
          _buildSettingInput('0'),
        ),
        _buildSettingRow(
          t['reconnection_attempts'] ?? 'Reconnection attempts',
          t['reconnection_attempts_desc'] ??
              'Maximum reconnection attempts when the connection closes abruptly.',
          _buildSettingInput('0'),
        ),
        _buildSettingRow(
          t['reconnection_intervals'] ?? 'Reconnection intervals',
          t['reconnection_intervals_desc'] ??
              'Interval between each reconnection attempt in milliseconds.',
          _buildSettingInput('5000'),
        ),
        _buildSettingRow(
          t['max_message_size'] ?? 'Maximum message size',
          t['max_message_size_desc'] ??
              'Maximum allowed message size in MB. To receive messages of any size, set to 0.',
          _buildSettingInput('10'),
        ),
      ],
    );
  }

  Widget _buildSettingRow(String title, String description, Widget trailing) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            flex: 3,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: const TextStyle(
                        fontSize: 12, fontWeight: FontWeight.w500)),
                const SizedBox(height: 4),
                Text(description,
                    style: const TextStyle(color: Colors.grey, fontSize: 12)),
              ],
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            flex: 2,
            child: Align(
              alignment: Alignment.centerLeft,
              child: trailing,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSettingInput(String value) {
    return SizedBox(
      width: 80,
      height: 32,
      child: TextField(
        controller: TextEditingController(text: value),
        style: TextStyle(
            color: Theme.of(context).textTheme.bodyMedium?.color,
            fontSize: 12,
            fontFamily: 'Consolas'),
        decoration: InputDecoration(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(4.0),
            borderSide: BorderSide(color: Theme.of(context).dividerColor),
          ),
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 8, vertical: 0),
        ),
      ),
    );
  }
}
