import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../data/local/database_helper.dart';

class ThemeModeNotifier extends StateNotifier<ThemeMode> {
  ThemeModeNotifier({ThemeMode? initial}) : super(initial ?? ThemeMode.system) {
    if (initial == null) {
      _load();
    }
  }

  Future<void> _load() async {
    final val = await DatabaseHelper.instance.getKeyValue('theme_mode');
    if (val == 'light') {
      state = ThemeMode.light;
    } else if (val == 'dark')
      state = ThemeMode.dark;
    else
      state = ThemeMode.system;
  }

  Future<void> setThemeMode(ThemeMode mode) async {
    state = mode;
    await DatabaseHelper.instance.setKeyValue('theme_mode', mode.name);
  }
}

final themeModeProvider =
    StateNotifierProvider<ThemeModeNotifier, ThemeMode>((ref) {
  return ThemeModeNotifier();
});

class SaveResponsesNotifier extends StateNotifier<bool> {
  SaveResponsesNotifier() : super(false) {
    _load();
  }

  Future<void> _load() async {
    final val = await DatabaseHelper.instance.getKeyValue('save_responses');
    if (val != null) state = val == 'true';
  }

  Future<void> setSaveResponses(bool save) async {
    state = save;
    await DatabaseHelper.instance
        .setKeyValue('save_responses', save.toString());
  }
}

final saveResponsesProvider =
    StateNotifierProvider<SaveResponsesNotifier, bool>((ref) {
  return SaveResponsesNotifier();
});

class LocaleNotifier extends StateNotifier<Locale> {
  LocaleNotifier({Locale? initial}) : super(initial ?? const Locale('en')) {
    if (initial == null) {
      _load();
    }
  }

  Future<void> _load() async {
    final val = await DatabaseHelper.instance.getKeyValue('locale');
    if (val != null) state = Locale(val);
  }

  Future<void> setLocale(Locale locale) async {
    state = locale;
    await DatabaseHelper.instance.setKeyValue('locale', locale.languageCode);
  }
}

final localeProvider = StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  return LocaleNotifier();
});

class NetworkSettings {
  final int requestTimeout;
  final int maxResponseSize;
  final bool sslVerification;
  final bool disableCookies;
  final bool systemProxy;
  final bool customProxyEnabled;
  final String customProxyUrl;
  final bool sendNoCacheHeader;
  final bool captureSystemProxyEnabled;
  final int captureProxyPort;
  final bool enableSslProxying;

  NetworkSettings({
    this.requestTimeout = 0,
    this.maxResponseSize = 50,
    this.sslVerification = false,
    this.disableCookies = false,
    this.systemProxy = true,
    this.customProxyEnabled = false,
    this.customProxyUrl = '',
    this.sendNoCacheHeader = true,
    this.captureSystemProxyEnabled = false,
    this.captureProxyPort = 8888,
    this.enableSslProxying = true,
  });

  NetworkSettings copyWith({
    int? requestTimeout,
    int? maxResponseSize,
    bool? sslVerification,
    bool? disableCookies,
    bool? systemProxy,
    bool? customProxyEnabled,
    String? customProxyUrl,
    bool? sendNoCacheHeader,
    bool? captureSystemProxyEnabled,
    int? captureProxyPort,
    bool? enableSslProxying,
  }) {
    return NetworkSettings(
      requestTimeout: requestTimeout ?? this.requestTimeout,
      maxResponseSize: maxResponseSize ?? this.maxResponseSize,
      sslVerification: sslVerification ?? this.sslVerification,
      disableCookies: disableCookies ?? this.disableCookies,
      systemProxy: systemProxy ?? this.systemProxy,
      customProxyEnabled: customProxyEnabled ?? this.customProxyEnabled,
      customProxyUrl: customProxyUrl ?? this.customProxyUrl,
      sendNoCacheHeader: sendNoCacheHeader ?? this.sendNoCacheHeader,
      captureSystemProxyEnabled:
          captureSystemProxyEnabled ?? this.captureSystemProxyEnabled,
      captureProxyPort: captureProxyPort ?? this.captureProxyPort,
      enableSslProxying: enableSslProxying ?? this.enableSslProxying,
    );
  }
}

class NetworkSettingsNotifier extends StateNotifier<NetworkSettings> {
  NetworkSettingsNotifier() : super(NetworkSettings()) {
    _load();
  }

  Future<void> _load() async {
    final timeout =
        await DatabaseHelper.instance.getKeyValue('request_timeout');
    final maxResponse =
        await DatabaseHelper.instance.getKeyValue('max_response_size');
    final sslVerif =
        await DatabaseHelper.instance.getKeyValue('ssl_verification');
    final disCookies =
        await DatabaseHelper.instance.getKeyValue('disable_cookies');
    final sysProxy = await DatabaseHelper.instance.getKeyValue('system_proxy');
    final customProxyEn =
        await DatabaseHelper.instance.getKeyValue('custom_proxy_enabled');
    final customProxyUrl =
        await DatabaseHelper.instance.getKeyValue('custom_proxy_url');
    final noCache =
        await DatabaseHelper.instance.getKeyValue('send_no_cache_header');
    final captureSysProxy = await DatabaseHelper.instance
        .getKeyValue('capture_system_proxy_enabled');
    final capturePort =
        await DatabaseHelper.instance.getKeyValue('capture_proxy_port');
    final enableSsl =
        await DatabaseHelper.instance.getKeyValue('enable_ssl_proxying');

    state = state.copyWith(
      requestTimeout: timeout != null ? int.tryParse(timeout) : null,
      maxResponseSize: maxResponse != null ? int.tryParse(maxResponse) : null,
      sslVerification: sslVerif != null ? sslVerif == 'true' : null,
      disableCookies: disCookies != null ? disCookies == 'true' : null,
      systemProxy: sysProxy != null ? sysProxy == 'true' : null,
      customProxyEnabled:
          customProxyEn != null ? customProxyEn == 'true' : null,
      customProxyUrl: customProxyUrl,
      sendNoCacheHeader: noCache != null ? noCache == 'true' : null,
      captureSystemProxyEnabled:
          captureSysProxy != null ? captureSysProxy == 'true' : null,
      captureProxyPort: capturePort != null ? int.tryParse(capturePort) : null,
      enableSslProxying: true, // Always true
    );
  }

  Future<void> updateSettings(NetworkSettings newSettings) async {
    state = newSettings;
    await DatabaseHelper.instance
        .setKeyValue('request_timeout', newSettings.requestTimeout.toString());
    await DatabaseHelper.instance.setKeyValue(
        'max_response_size', newSettings.maxResponseSize.toString());
    await DatabaseHelper.instance.setKeyValue(
        'ssl_verification', newSettings.sslVerification.toString());
    await DatabaseHelper.instance
        .setKeyValue('disable_cookies', newSettings.disableCookies.toString());
    await DatabaseHelper.instance
        .setKeyValue('system_proxy', newSettings.systemProxy.toString());
    await DatabaseHelper.instance.setKeyValue(
        'custom_proxy_enabled', newSettings.customProxyEnabled.toString());
    await DatabaseHelper.instance
        .setKeyValue('custom_proxy_url', newSettings.customProxyUrl);
    await DatabaseHelper.instance.setKeyValue(
        'send_no_cache_header', newSettings.sendNoCacheHeader.toString());
    await DatabaseHelper.instance.setKeyValue('capture_system_proxy_enabled',
        newSettings.captureSystemProxyEnabled.toString());
    await DatabaseHelper.instance.setKeyValue(
        'capture_proxy_port', newSettings.captureProxyPort.toString());
    await DatabaseHelper.instance.setKeyValue(
        'enable_ssl_proxying', newSettings.enableSslProxying.toString());
  }
}

final networkSettingsProvider =
    StateNotifierProvider<NetworkSettingsNotifier, NetworkSettings>((ref) {
  return NetworkSettingsNotifier();
});

// A simple localization provider that returns strings based on current locale
final translationsProvider = Provider<Map<String, String>>((ref) {
  final locale = ref.watch(localeProvider);
  if (locale.languageCode == 'zh') {
    return _zh;
  }
  return _en;
});

const _en = {
  'failed_to_load_certificat': 'Failed to load certificate info: ',
  'no_certificate_info': 'No certificate info',
  'import_certificate': 'Import Certificate',
  'regenerate_certificate': 'Regenerate Certificate',
  'export_certificate': 'Export Certificate',
  'certificate_info': 'Certificate Info',
  'not_installed': 'Not Installed',
  'certificate_path': 'Certificate Path',
  'private_key_path': 'Private Key Path',
  'subject': 'Subject',
  'issuer': 'Issuer',
  'validity': 'Validity',
  'pem_preview': 'PEM Preview',
  'certificate_imported_plea':
      'Certificate imported. Please restart your browser.',
  'regenerate_root_certifica': 'Regenerate Root Certificate',
  'after_regeneration_the_ol':
      'After regeneration, the old certificate will be invalid. Continue?',
  'root_certificate_regenera':
      'Root certificate regenerated. Please install and trust it.',
  'failed_to_regenerate_cert': 'Failed to regenerate certificate: ',
  'export_root_certificate': 'Export Root Certificate',
  'certificate_exported_to': 'Certificate exported to ',
  'failed_to_export_certific': 'Failed to export certificate: ',
  'export_password': 'Export Password',
  'can_be_empty': 'Can be empty',
  'root_certificate_manageme':
      'Root certificate management has moved to the capture page.',
  'failed_to_load_cert_info': 'Failed to load certificate info: ',
  'cert_exported_to': 'Certificate exported to ',
  'failed_to_export_cert': 'Failed to export certificate: ',

  'discard': 'Discard',
  'save_and_close': 'Save and Close',
  'tree_view_coming_soon': 'Tree view coming soon',
  'enable_server_certificate_verification':
      'Enable server certificate verification',
  'verify_server_certificate_desc':
      'Verify server certificate when connecting to a broker over a secure connection.',
  'clean_session': 'Clean Session',
  'clean_session_desc':
      'Configure if the broker should start with a fresh connection without retaining any previous session data.',
  'session_expiry_interval': 'Session Expiry Interval',
  'session_expiry_interval_desc':
      'Configure the session expiry interval in seconds. This impacts how long a broker will store the session data for your client. If clean start is on, this value is ignored.',
  'keep_alive': 'Keep Alive',
  'keep_alive_desc': 'Configure the keep alive interval in seconds.',
  'auto_reconnect': 'Auto Reconnect',
  'auto_reconnect_desc':
      'Configure if the client should automatically reconnect on abrupt disconnection.',
  'connection_timeout': 'Connection Timeout',
  'connection_timeout_desc': 'Configure the connection timeout in seconds.',
  'receive_maximum': 'Receive Maximum',
  'receive_maximum_desc':
      'Configure the maximum number of QoS 1 and 2 messages that can be processed concurrently.',
  'maximum_packet_size': 'Maximum Packet Size',
  'maximum_packet_size_desc':
      'Configure the maximum packet size in bytes that the client will accept.',
  'key_0': '导出',
  'crt': '导出根公钥证书 (.crt)',
  'pem': '导出根公钥证书 (.pem)',
  'p12': '导出 .p12',
  'not_found': 'Not found',
  'variables': 'Variables',
  'variable': 'Variable',
  'globals': 'Globals',
  'no_recent_items': 'No recent items',
  'recently_viewed': 'RECENTLY VIEWED',
  'environment_optional': 'Environment (optional)',
  'no_messages_yet': 'No messages yet',
  'publish': 'Publish',
  'query_parameters': 'Query Parameters',
  'schema': 'Schema',
  'beautify': 'Beautify',
  'this_request_does_not_hav': 'This request does not have a body',
  'clear_file': 'Clear File',
  'query': 'QUERY',
  'graphql_variables': 'GRAPHQL VARIABLES',
  'current_token': 'Current Token',
  'configure_new_token': 'Configure New Token',
  'get_new_access_token': 'Get New Access Token',
  'enter_url_and_click_send': 'Enter URL and click Send to get a response',
  'requested_1_times': 'Requested 1 times',
  'save_response_to_file': 'Save response to file',
  'clear_response': 'Clear response',
  'response_time': 'Response Time',
  'request_size': 'Request Size',
  'http_version': 'HTTP Version',
  'local_address': 'Local Address',
  'remote_address': 'Remote Address',
  'no_headers': 'No Headers',
  'key': 'Key:',
  'no_cookies': 'No Cookies',
  'expires': 'Expires',
  'httponly': 'HttpOnly',
  'secure': 'Secure',
  'no_test_results': 'No Test Results',
  'view_in_console': 'View in console',
  'save_to': 'Save to ',
  'save_request': 'SAVE REQUEST',
  'request_name': 'Request name',
  'description': 'Description',
  'under_construction': 'Under construction...',
  'keyboard_shortcuts': 'Keyboard Shortcuts',
  'through': 'through',
  'export_data': 'Export Data',
  'export_data_success': 'Data exported successfully!',
  'export_data_failed': 'Failed to export data:',
  'import_data_success': 'Data imported successfully!',
  'import_data_failed': 'Failed to import data:',
  'export_all_your_collectio':
      'Export all your collections, environments, globals and header presets to a single dump file.',
  'import_your_data_from_a_p': 'Import your data from a previous export.',
  'capture_proxy_mitm': 'Capture Proxy (MITM)',
  'enable_ssl_proxying': 'Enable SSL Proxying',
  'enable_ssl_proxying_desc':
      'Decrypt HTTPS traffic. Requires installing the CA certificate.',
  'use_system_proxy': 'Use System Proxy',
  'use_system_proxy_desc': 'Use the system proxy for sending requests.',
  'add_custom_proxy': 'Add a custom proxy configuration',
  'proxy_server_hint': 'e.g. 127.0.0.1:8080 or http://proxy:80',
  'proxy_server': 'Proxy Server',
  'postlens': 'PostLens',
  'version_1_0_0': 'Version 1.0.0',
  'grpc_request': 'gRPC Request',
  'websocket_request': 'WebSocket Request',
  'socket_request': 'Socket Request',
  'mqtt_request': 'MQTT Request',
  'clear_history': 'Clear History',
  'add_request': 'Add request',
  'add_folder': 'Add folder',
  'more': 'More',
  'new_folder': 'New Folder',
  'secret_key': 'Secret Key:',
  'public_key_pem': 'Public Key (PEM):',
  'private_key_pem': 'Private Key (PEM):',
  'key_config': 'Key / Config:',
  'generate_sm2_keys': 'Generate SM2 Keys',
  'app_secret': 'App Secret:',
  'generate_uuid_v1_time_bas': 'Generate UUID v1 (Time-based)',
  'generate_uuid_v4_random': 'Generate UUID v4 (Random)',
  'pattern': 'Pattern:',
  'qr_code_preview': 'QR Code Preview',
  'export_image': 'Export Image',
  'no_image_rendered': 'No Image Rendered',
  'create_new_workspace': 'CREATE NEW WORKSPACE',
  'summary': 'Summary',
  'create_workspace': 'Create Workspace',

  'settings': 'Settings',
  'general': 'General',
  'themes': 'Themes',
  'shortcuts': 'Shortcuts',
  'data': 'Data',
  'proxy': 'Proxy',
  'about': 'About',
  'theme': 'Theme',
  'test_results': 'Test Results',
  'request_timeout': 'Request timeout',
  'request_timeout_desc':
      'Set how long a request should wait for a response before timing out. To never time out, set to 0.',
  'max_response_size': 'Max response size',
  'max_response_size_desc':
      'Set the maximum size of a response to download. To download a response of any size, set to 0.',
  'ssl_cert_verification': 'SSL certificate verification',
  'disable_cookies_setting': 'Disable cookies',
  'disable_cookies_desc': 'Disable cookie jar for all requests.',
  'send_no_cache_header': 'Send no-cache header',
  'system_mode': 'Follow System',
  'light_mode': 'Light Mode',
  'dark_mode': 'Dark Mode',

  // Shortcuts
  'Tabs': 'Tabs',
  'Sidebar': 'Sidebar',
  'Request': 'Request',
  'Interface': 'Interface',
  'Window and modals': 'Window and modals',
  'Close Tab': 'Close Tab',
  'Force Close Tab': 'Force Close Tab',
  'Switch To Next Tab': 'Switch To Next Tab',
  'Switch To Previous Tab': 'Switch To Previous Tab',
  'Switch To Tab at Position': 'Switch To Tab at Position',
  'Switch To Last Tab': 'Switch To Last Tab',
  'Reopen Last Closed Tab': 'Reopen Last Closed Tab',
  'New Runner Tab': 'New Runner Tab',
  'Search Tabs': 'Search Tabs',
  'Search Sidebar': 'Search Sidebar',
  'Next Item': 'Next Item',
  'Previous Item': 'Previous Item',
  'Expand Item': 'Expand Item',
  'Expand All': 'Expand All',
  'Collapse Item': 'Collapse Item',
  'Collapse All': 'Collapse All',
  'Select Item': 'Select Item',
  'Rename Item': 'Rename Item',
  'Cut Item': 'Cut Item',
  'Copy Item': 'Copy Item',
  'Paste Item': 'Paste Item',
  'Duplicate Item': 'Duplicate Item',
  'Delete Item': 'Delete Item',
  'Request URL': 'Request URL',
  'Save Request As': 'Save Request As',
  'Send Request': 'Send Request',
  'Send And Download Request': 'Send And Download Request',
  'Send Request with AI': 'Send Request with AI',
  'Zoom In': 'Zoom In',
  'Zoom Out': 'Zoom Out',
  'Reset Zoom': 'Reset Zoom',
  'Toggle Two-Pane View': 'Toggle Two-Pane View',
  'Toggle Left Sidebar': 'Toggle Left Sidebar',
  'Toggle Right Sidebar': 'Toggle Right Sidebar',
  'Toggle Workbench': 'Toggle Workbench',
  'Swap Sidebars': 'Swap Sidebars',
  'Reset Layout': 'Reset Layout',
  'Environment Selector': 'Environment Selector',
  'New...': 'New...',
  'New PostLens Window': 'New PostLens Window',
  'New Console Window': 'New Console Window',
  'Find': 'Find',
  'Open Shortcut Help': 'Open Shortcut Help',
  'Search in Current Workspace': 'Search in Current Workspace',
  'Open Agent Mode': 'Open Agent Mode',
  'Open Vault': 'Open Vault',
  'Cancel Conversation': 'Cancel Conversation',
  'Accept All': 'Accept All',
  'Reject All': 'Reject All',

  'language': 'Language',
  'english': 'English',
  'chinese': 'Chinese',
  'close': 'Close',
  'my_workspace': 'My Workspace',
  'home': 'Home',
  'workspaces': 'Workspaces',
  'api_network': 'API Network',
  'search': 'Search',
  'no_environment': 'No Environment',
  'new_environment': 'New Environment',
  'no_collections': 'No collections',
  'no_history': 'No history',
  'no_files': 'No files',
  'no_tools': 'No tools',
  'no_workspaces': 'No workspaces found',
  'all_workspaces': 'All Workspaces',
  'view_all_workspaces': 'View all workspaces',
  'new_request': 'New Request',
  'send': 'Send',
  'params': 'Params',
  'authorization': 'Authorization',
  'headers': 'Headers',
  'body': 'Body',
  'pre_request_script': 'Pre-request Script',
  'tests': 'Tests',
  'collections': 'Collections',
  'environments': 'Environments',
  'history': 'History',
  'files': 'Files',
  'filter': 'Filter',
  'new_collection': 'New Collection',
  'http_request': 'HTTP Request',
  'request_history': 'REQUEST HISTORY',
  'clear_all': 'Clear all',
  'import': 'Import',
  'save_responses': 'Save Responses',
  'status': 'Status',
  'time': 'Time',
  'size': 'Size',
  'response_body': 'Response Body',
  'cookies': 'Cookies',
  'console': 'Console',
  'clear': 'Clear',
  'cancel': 'Cancel',
  'save': 'Save',
  'create': 'Create',
  'create_variable': 'Create',
  'current_environment': 'Current Environment',
  'enter_value': 'Enter value',
  'please_enter_value': 'Please enter a value',
  'empty': 'empty',
  'environment': 'Environment',
  'global': 'Global',
  'rename': 'Rename',
  'duplicate': 'Duplicate',
  'delete': 'Delete',
  'overview': 'Overview',
  'environment_coming_soon': 'Environment feature coming soon',
  'capture': 'Capture',
  'overview_tab': 'Overview',
  'raw_tab': 'Raw',
  'headers_tab': 'Headers',
  'body_tab': 'Body',
  'raw_request_data': 'Raw Request Data',
  'body_empty_or_binary': 'Body is empty or binary',
  'method': 'Method',
  'protocol': 'Protocol',
  'server_address': 'Server Address',
  'stream': 'Stream',
  'proxy_protocol': 'Proxy Protocol',
  'application': 'Application',
  'name': 'Name',
  'path': 'Path',
  'process_id': 'Process ID',
  'connection': 'Connection',
  'frontend': 'Frontend',
  'client_address': ' - Client Address',
  'client_port': ' - Client Port',
  'server_address_sub': ' - Server Address',
  'server_port': ' - Server Port',
  'backend': 'Backend',
  'version': 'Version',
  'select_alpn': 'Select ALPN',
  'cipher_suite_list': 'Cipher Suite List',
  'select_cipher_suite': 'Select Cipher Suite',
  'request_start': 'Request Start',
  'request_end': 'Request End',
  'total_duration': 'Total Duration',
  'request': 'Request',
  'response': 'Response',
  'total': 'Total',
  'cannot_parse_color': 'Cannot parse color format',
  'copied': 'Copied',
  'color_palette_conversion': 'Color Palette / Multi-format Conversion',
  'input_color_support': 'Input color (supports HEX / RGB / HSL / CMYK)',
  'preview': 'Preview',
  'edit': 'Edit',
  'rich_text': 'Rich Text',
  'markdown': 'Markdown',
  'doc': 'Doc',
  'preset_palette': 'Preset Palette',
  'copy_hex': 'Copy HEX',
  'reset': 'Reset',
  'copy': 'Copy',
  'base64_encode_decode': 'Base64 Encode/Decode',
  'url_encode_decode': 'URL Encode/Decode',
  'jwt_decode': 'JWT Decode',
  'json_escape': 'JSON Escape',
  'sm_algorithms': 'SM (SM2/SM3/SM4) Algorithms',
  'api_signature_verification':
      'API Signature Verification (Demo: Key sort + Secret + MD5)',
  'file_md5_calc': 'File MD5 Calculation',
  'select_file': 'Select File',
  'file_path_label': 'File Path: ',
  'md5_result_label': 'MD5 Result:',
  'rsa_encrypt_decrypt': 'RSA Encrypt/Decrypt',
  'seconds': 'Seconds(s)',
  'milliseconds': 'Milliseconds(ms)',
  'current_timestamp': 'Current Timestamp',
  'second_unit': 'Second',
  'millisecond_unit': 'Millisecond',
  'switch_unit': 'Switch Unit',
  'start': 'Start',
  'stop': 'Stop',
  'single_conversion': 'Single Conversion',
  'batch_conversion': 'Batch Conversion',
  'ts_to_datetime': 'Timestamp to DateTime',
  'convert': 'Convert',
  'conversion_result': 'Conversion Result',
  'datetime_to_ts': 'DateTime to Timestamp',
  'generate_quantity': 'Generate Quantity:',
  'uuid_generator': 'UUID Generator',
  'regex_testing': 'Regex Testing',
  'text_to_qrcode': 'Text <-> QR Code',
  'json_format_minify': 'JSON Format/Minify',
  'xml_format': 'XML Format (Simple)',
  'text_hex_dump': 'Text <-> Hex Dump',
  'image_base64': 'Image <-> Base64',
  'tool_encode_decode': 'Encode/Decode',
  'tool_encrypt_decrypt': 'Encrypt/Decrypt',
  'tool_view': 'View',
  'tool_other': 'Other',
  'tool_base64': 'Base64',
  'tool_url': 'URL',
  'tool_jwt': 'JWT',
  'tool_json_escape': 'JSON Escape',
  'tool_hash': 'Hash',
  'tool_file_md5': 'File MD5',
  'tool_hmac': 'HMAC',
  'tool_aes': 'AES',
  'tool_rsa': 'RSA',
  'tool_sm': 'SM Algorithms',
  'tool_api_signature': 'API Signature',
  'tool_json': 'JSON',
  'tool_xml': 'XML',
  'tool_hex': 'Hex',
  'tool_image': 'Image',
  'tool_color': 'Color',
  'tool_timestamp': 'Timestamp',
  'tool_uuid': 'UUID',
  'tool_regex': 'Regex',
  'tool_qrcode': 'QR Code',
  'no_open_tabs': 'No open tabs currently',
  'quick_create_hint':
      'You can quickly create new requests or workspaces, or import existing data to continue working.',
  'import_data': 'Import Data',
  'open_workspace_overview': 'Open Workspace Overview',
  'open_settings': 'Open Settings',
  'proxy_port': 'Proxy port',
  'system_proxy_enabled': 'System proxy enabled',
  'system_proxy_disabled': 'System proxy not enabled',
  'start_capture_hint':
      'After clicking start capture, it will automatically start the local proxy and try to enable the system proxy',
  'stop_capture': 'Stop Capture',
  'start_capture': 'Start Capture',
  'proxy_conflict_title': 'Other Proxy Software Detected',
  'proxy_conflict_content':
      'The system currently has other proxy software enabled, which may conflict with the packet capture function. It is recommended that you close other proxy software first, and then try again.',
  'got_it': 'Got it',
  'system_proxy_is_on': 'System proxy is on',
  'only_switch_proxy': 'Only switch proxy',
  'please_start_capture_first': 'Please start capture first',
  'cert_installed': 'Cert Installed',
  'install_root_cert': 'Install Root Cert',
  'copy_current_item': 'Copy Current Item',
  'copied_to_clipboard': 'Copied to clipboard',
  'close_capture_page': 'Close Capture Page',
  'search_url_host': 'Search URL / Host',
  'listening': 'Listening',
  'not_started': 'Not started',
  'no_data': 'No data',
  'icon': 'Icon',
  'status_code': 'Status Code',
  'server_ip': 'Server IP',
  'duration': 'Duration',
  'request_and_response': 'Request & Response',
  'no': 'No',
  'connect_tunnel_no_body': 'CONNECT tunnel has no readable request body',
  'no_request_body': 'No Request Body',
  'https_not_decrypted':
      'HTTPS content not decrypted (currently in tunnel mode)',
  'no_response_body': 'No Response Body',
  'search_coming_soon': 'Search function coming soon',
  'save_data': 'Save Data',
  'saved_to': 'Saved to ',
  'copy_curl': 'Copy cURL',
  'curl_copied': 'cURL copied',
  'view_details': 'View Details',
  'select_request_view_details': 'Select a request to view details',
  'install_mitm_root_cert': 'Install MITM Root Certificate',
  'install_cert_desc':
      'To decrypt HTTPS requests, you need to install and trust our root certificate in the system. Please perform the following steps:',
  'cert_path': 'Certificate Path:',
  'install_trust_command': 'Install and Trust Command:',
  'command_copied': 'Command copied to clipboard',
  'install_cert_hint':
      'Hint: After completion, you may need to restart the browser or related applications for the certificate to take effect.',
  'auto_execute_command': 'Auto Execute (Requires privileges)',
  'auto_command_not_supported':
      'Auto command generation is not supported for this OS currently',
  'linux_manual_execute':
      'For Linux, please execute the above command manually in the terminal',
  'cert_install_success': 'Certificate installed successfully!',
  'install_failed': 'Installation failed:',
  'auth_type': 'Auth Type',
  'auth_header_auto_gen':
      'The authorization header will be automatically generated when you send the request.',
  'no_auth': 'No Auth',
  'no_auth_desc': 'This request does not use any authorization. ',
  'token': 'Token',
  'username': 'Username',
  'password': 'Password',
  'value': 'Value',
  'add_to': 'Add to',
  'algorithm': 'Algorithm',
  'secret': 'Secret',
  'secret_base64_encoded': 'Secret Base64 encoded',
  'payload': 'Payload',
  'advanced_configuration': 'Advanced configuration',
  'request_header_prefix': 'Request header prefix',
  'jwt_headers': 'JWT headers',
  'filter_application': 'Application',
  'filter_domain': 'Domain',
  'filter_method': 'Method',
  'filter_status_code': 'Status Code',
  'filter_resource_type': 'Resource Type',
  'filter_contains': 'Contains',
  'filter_equals': 'Equals',
  'filter_not_equals': 'Not Equals',
  'filter_not_contains': 'Not Contains',
  'add_filter_condition': 'Add Filter Condition',
  'no_filters': 'No filters added yet.',
  'remove_filter': 'Remove',
  'add_filter': 'Add',
  'global_variables': 'Global Variables',
  'global_variables_desc':
      'These variables are available in all requests. Use {{variable_name}} syntax to reference them.',
  'show_timestamps': 'Show Timestamps',
  'hide_network': 'Hide Network',

  // Tool Strings
  'text_utf8': 'Text (UTF-8)',
  'enter_text_here': 'Enter text here...',
  'base64': 'Base64',
  'enter_base64_here': 'Enter Base64 here...',
  'encode': 'Encode',
  'decode': 'Decode',
  'error_encoding': 'Error encoding: ',
  'error_decoding': 'Error decoding: ',
  'hash': 'Hash',
  'enter_text_to_hash': 'Enter text to hash...',
  'hex': 'Hex',
  'text': 'Text',
  'hex_dump': 'Hex Dump',
  'text_to_hex': 'Text -> Hex',
  'hex_to_text': 'Hex -> Text',
  'error_decoding_hex': 'Error decoding Hex: ',
  'invalid_hex_length': 'Invalid hex string length',
  'aes_key_hint': 'AES Key (auto padded to 32 chars)',
  'iv_hint': 'IV (auto padded to 16 chars)',
  'aes_cbc_pkcs7': 'AES (CBC/PKCS7)',
  'plaintext': 'Plaintext',
  'text_to_encrypt': 'Text to encrypt',
  'ciphertext_base64': 'Ciphertext (Base64)',
  'base64_ciphertext': 'Base64 ciphertext',
  'encrypt': 'Encrypt',
  'decrypt': 'Decrypt',
  'error': 'Error: ',
  'hmac': 'HMAC',
  'enter_text_to_sign': 'Enter text to sign...',
  'hmac_hex': 'HMAC Hex',
  'compute_hmac': 'Compute HMAC',
  'image_base64_label': 'Image Base64',
  'render_image': 'Render Image',
  'select_image': 'Select Image',
  'invalid_image_base64': 'Invalid Image Base64: ',
  'image_exported_successfully': 'Image exported successfully!',
  'failed_to_export_image': 'Failed to export image: ',
  'failed_to_select_image': 'Failed to select image: ',
  'save_image': 'Save Image',
  'unescaped_string': 'Unescaped String',
  'escaped_string': 'Escaped String',
  'escape': 'Escape',
  'unescape': 'Unescape',
  'error_escaping': 'Error escaping: ',
  'error_unescaping': 'Error unescaping: ',
  'raw_json': 'Raw JSON',
  'formatted_json': 'Formatted JSON',
  'minify': 'Minify',
  'invalid_json': 'Invalid JSON: ',
  'jwt_token': 'JWT Token',
  'decoded_payload': 'Decoded Payload',
  'invalid_jwt_token':
      'Invalid JWT token (must have 3 parts separated by dots)',
  'error_decoding_jwt': 'Error decoding JWT: ',
  'unit': 'Unit',
  'timezone': 'Timezone',
  'generated_uuids': 'Generated UUIDs',
  'test_text': 'Test Text',
  'matches': 'Matches',
  'test_match': 'Test Match',
  'please_enter_pattern': 'Please enter a pattern',
  'no_matches_found': 'No matches found.',
  'found_matches': 'Found matches:\n',
  'match': 'Match',
  'group': 'Group',
  'regex_error': 'Regex Error: ',
  'text_url': 'Text / URL',
  'enter_text_to_generate_qr': 'Enter text to generate QR code',
  'generate_qr': 'Generate QR',
  'recognize_qr': 'Recognize QR',
  'failed_to_recognize_qr': 'Failed to recognize QR code: ',
  'save_qr_code': 'Save QR Code',
  'qr_code_exported_successfully': 'QR Code exported successfully!',
  'failed_to_export_qr': 'Failed to export QR code: ',
  'encrypt_with_public': 'Encrypt (with Public Key)',
  'decrypt_with_private': 'Decrypt (with Private Key)',
  'encryption_error': 'Encryption Error: ',
  'decryption_error': 'Decryption Error: ',
  'enter_32_char_hex_key':
      'Enter 32-char Hex key for SM4, or click generate for SM2',
  'generated_sm2_key_pair': 'Generated SM2 Key Pair',
  'error_generating_keys': 'Error generating keys: ',
  'sm4_key_must_be_32_hex':
      'SM4 Key must be exactly 32 hex characters (16 bytes).',
  'please_generate_sm2_keys_first': 'Please generate SM2 keys first.',
  'input_data': 'Input Data',
  'output_result': 'Output Result',
  'compute': 'Compute',
  'decoded_text': 'Decoded Text',
  'url_encode_hint_1': 'https://example.com/?q=test',
  'encoded_url': 'Encoded URL',
  'url_encode_hint_2': 'https%3A%2F%2Fexample.com%2F%3Fq%3Dtest',
  'raw_xml': 'Raw XML',
  'formatted_xml': 'Formatted XML',
  'error_formatting_xml': 'Error formatting XML: ',
  'input_color_hint':
      '#FF0000 / rgb(255,0,0) / hsl(0,100%,50%) / cmyk(0%,100%,100%,0%)',
  'calculating': 'Calculating...',

  // WebSocket, Socket, MQTT pages
  'ws': 'WS',
  'connect': 'Connect',
  'disconnect': 'Disconnect',
  'connected': 'Connected',
  'disconnected': 'Disconnected',
  'connected_to': 'Connected to',
  'disconnected_from': 'Disconnected from server',
  'connection_closed_by_server': 'Connection closed by server',
  'failed_to_connect': 'Failed to connect',
  'connect_error': 'Connect Error',
  'message': 'Message',
  'messages': 'Messages',
  'all_messages': 'All Messages',
  'clear_messages': 'Clear Messages',
  'enter_message_here': 'Enter message here',
  'format': 'Format',
  'show_auto_headers': 'Show auto-generated headers',
  'hide_auto_headers': 'Hide auto-generated headers',
  'auto_generated': 'Auto-generated',
  'enable_cert_verification': 'Enable server certificate verification',
  'cert_verification_desc':
      'Verify server certificate when connecting over a secure connection.',
  'handshake_timeout': 'Handshake request timeout',
  'handshake_timeout_desc':
      'Set how long the handshake request should wait before timing out in milliseconds. To never time out, set to 0.',
  'reconnection_attempts': 'Reconnection attempts',
  'reconnection_attempts_desc':
      'Maximum reconnection attempts when the connection closes abruptly.',
  'reconnection_intervals': 'Reconnection intervals',
  'reconnection_intervals_desc':
      'Interval between each reconnection attempt in milliseconds.',
  'max_message_size': 'Maximum message size',
  'max_message_size_desc':
      'Maximum allowed message size in MB. To receive messages of any size, set to 0.',
  'enter_url': 'Enter URL',
  'select_protocol': 'Select Protocol',
  'untitled_request': 'Untitled Request',
  'today': 'Today',
  'yesterday': 'Yesterday',

  // API Signature Tool
  'api_sign_cert_file': 'Certificate File',
  'api_sign_key_text': 'Key Text',
  'api_sign_choose_file': 'Choose File',
  'api_sign_no_file_selected': 'No file selected',
  'api_sign_app_private_key': 'Application Private Key (PEM)',
  'api_sign_params': 'Parameters (JSON) / Plaintext',
  'api_sign_charset': 'Charset: ',
  'api_sign_type': 'Sign Type: ',
  'api_sign_start_sign': 'Sign',
  'api_sign_signature_result': 'Signature Result',
  'api_sign_platform_public_key': 'Platform Public Key (PEM)',
  'api_sign_notify_params': 'Notification Params (JSON) / Plaintext',
  'api_sign_signature_to_verify': 'Signature to Verify',
  'api_sign_signature_to_verify_hint':
      'If JSON contains "sign", this can be empty.',
  'api_sign_start_verify': 'Verify',
  'api_sign_verification_result': 'Verification Result',
  'api_sign_tab_sign': 'Sign',
  'api_sign_tab_verify': 'Verify',
  'api_sign_verify_success': 'Verify Success',
  'api_sign_verify_failed': 'Verify Failed',
  'api_sign_error_private_key_empty': 'Private key text is empty',
  'api_sign_error_cert_not_selected': 'Certificate file not selected',
  'api_sign_error_no_private_key_p12': 'No private key found in P12',
  'api_sign_error_public_key_empty': 'Public key text is empty',
  'api_sign_error_no_public_key_p12': 'No valid public key found in P12',
  'api_sign_error_signature_empty': 'Signature to verify is empty',

  // Socket.IO specific
  'events': 'Events',
  'listen': 'Listen',
  'add_event': 'Add event',
  'add_description': 'Add description',
  'compose_message': 'Compose message',
  'event_name_default': 'Event name, defaults to "message"',
  'client_version': 'Client version',
  'client_version_desc':
      'Choose client version that should be used for connecting with the server.',
  'handshake_path': 'Handshake path',
  'handshake_path_desc':
      'Set the server path that should be used during the handshake request.',
  'connect_to_send': 'Connect to send and receive messages',
  'ack_received': 'Ack received',
  'arg': 'Arg',
  'ack': 'Ack',

  // MQTT specific
  'topics': 'Topics',
  'subscribe': 'Subscribe',
  'add_topic': 'Add Topic',
  'properties': 'Properties',
  'last_will': 'Last Will',
  'basic_auth': 'Basic Auth',
  'retain': 'Retain',
  'will_delay': 'Will Delay',
  'mqtt_url_hint': 'mqtt://broker.hivemq.com:1883',
  'add_property': 'Add property',
  'add_value': 'Add Value',
  'topic_label': 'Topic',
  'unsubscribed_from': 'Unsubscribed from',
  'subscribed_to': 'Subscribed to',
  'qos': 'QoS',
  'parse_escape': 'Auto parse escape characters',
  'loop_send': 'Loop send',
  'log_mode': 'Log mode display',
  'auto_wrap': 'Auto word wrap',
  'hide_receive': 'Do not display received data',
  'auto_scroll': 'Auto scroll',
  'http_version_label': 'HTTP version',
  'http_version_desc':
      'Select the HTTP version to use for sending the request.',
  'enable_ssl_verification': 'Enable SSL certificate verification',
  'enable_ssl_verification_desc':
      'Verify SSL certificates when sending a request. Verification failures will result in the request being aborted.',
  'follow_redirects': 'Automatically follow redirects',
  'follow_redirects_desc': 'Follow HTTP 3xx responses as redirects.',
  'follow_original_http_method': 'Follow original HTTP Method',
  'follow_original_http_method_desc':
      'Redirect with the original HTTP method instead of the default behavior of redirecting with GET.',
  'follow_authorization_header': 'Follow Authorization header',
  'follow_authorization_header_desc':
      'Retain authorization header when a redirect happens to a different hostname.',
  'remove_referer_header': 'Remove referer header on redirect',
  'remove_referer_header_desc':
      'Remove the referer header when a redirect happens.',
  'enable_strict_http_parser': 'Enable strict HTTP parser',
  'enable_strict_http_parser_desc':
      'Restrict responses with invalid HTTP headers.',
  'encode_url_automatically': 'Encode URL automatically',
  'encode_url_automatically_desc':
      'Encode the URL\'s path, query parameters, and authentication fields.',
  'disable_cookie_jar': 'Disable cookie jar',
  'disable_cookie_jar_desc':
      'Prevent cookies used in this request from being stored in the cookie jar. Existing cookies in the cookie jar will not be added as headers for this request.',
  'use_server_cipher_suite': 'Use server cipher suite during handshake',
  'use_server_cipher_suite_desc':
      'Use the server\'s cipher suite order instead of the client\'s during handshake.',
  'max_redirects': 'Maximum number of redirects',
  'max_redirects_desc':
      'Set a cap on the maximum number of redirects to follow.',
  'disabled_protocols': 'TLS/SSL protocols disabled during handshake',
  'disabled_protocols_desc':
      'Specify the SSL and TLS protocol versions to be disabled during handshake. All other protocols will be enabled.',
  'cipher_suite_selection': 'Cipher suite selection',
  'cipher_suite_selection_desc':
      'Order of cipher suites that the SSL server profile uses to establish a secure connection.',
  'enter_cipher_suites': 'Enter cipher suites',
  'receive_settings': 'Receive Settings',
  'send_settings': 'Send Settings',
};

const _zh = {
  'enable_server_certificate_verification': '启用服务器证书验证',
  'verify_server_certificate_desc': '通过安全连接连接到代理时验证服务器证书。',
  'clean_session': '清除会话',
  'clean_session_desc': '配置代理是否应以全新连接启动，而不保留任何先前的会话数据。',
  'session_expiry_interval': '会话过期时间',
  'session_expiry_interval_desc':
      '配置会话过期时间（秒）。这会影响代理为您的客户端存储会话数据的时间。如果开启了全新启动（清除会话），则忽略此值。',
  'keep_alive': '保持活动',
  'keep_alive_desc': '配置保持活动时间（秒）。',
  'auto_reconnect': '自动重连',
  'auto_reconnect_desc': '配置客户端在意外断开连接时是否应自动重新连接。',
  'connection_timeout': '连接超时',
  'connection_timeout_desc': '配置连接超时时间（秒）。',
  'receive_maximum': '最大接收数',
  'receive_maximum_desc': '配置可并发处理的最大 QoS 1 和 2 消息数量。',
  'maximum_packet_size': '最大数据包大小',
  'maximum_packet_size_desc': '配置客户端将接受的最大数据包大小（字节）。',
  'failed_to_load_certificat': '加载证书信息失败: ',
  'no_certificate_info': '暂无证书信息',
  'import_certificate': '导入证书',
  'regenerate_certificate': '重新生成证书',
  'export_certificate': '导出证书',
  'certificate_info': '证书信息',
  'not_installed': '未安装',
  'certificate_path': '证书路径',
  'private_key_path': '私钥路径',
  'subject': '主题',
  'issuer': '签发者',
  'validity': '有效期',
  'pem_preview': 'PEM 预览',
  'certificate_imported_plea': '证书已导入到系统，请重启浏览器后再试',
  'regenerate_root_certifica': '重新生成根证书',
  'after_regeneration_the_ol': '重新生成后，旧证书将失效，需要重新安装并信任新证书。是否继续？',
  'root_certificate_regenera': '已重新生成根证书，请重新导入并信任新证书',
  'failed_to_regenerate_cert': '重新生成证书失败: ',
  'export_root_certificate': '导出根证书',
  'certificate_exported_to': '证书已导出到 ',
  'failed_to_export_certific': '导出证书失败: ',
  'export_password': '导出密码',
  'can_be_empty': '可留空',
  'root_certificate_manageme': '根证书管理已移动到抓包页面顶部的证书按钮中。',
  'failed_to_load_cert_info': '加载证书信息失败: ',
  'cert_exported_to': '证书已导出至 ',
  'failed_to_export_cert': '导出证书失败: ',

  'discard': '放弃',
  'save_and_close': '保存并关闭',
  'tree_view_coming_soon': '树状视图即将推出',
  'key_0': '导出',
  'crt': '导出根公钥证书 (.crt)',
  'pem': '导出根公钥证书 (.pem)',
  'p12': '导出 .p12',
  'not_found': '未找到',
  'variables': '变量',
  'variable': '变量',
  'globals': '全局变量',
  'no_recent_items': '暂无最近项目',
  'recently_viewed': '最近浏览',
  'environment_optional': '环境 (可选)',
  'no_messages_yet': '暂无消息',
  'publish': '发布',
  'query_parameters': '查询参数',
  'schema': 'Schema',
  'beautify': '格式化',
  'this_request_does_not_hav': '此请求没有请求体',
  'clear_file': '清除文件',
  'query': '查询',
  'graphql_variables': 'GRAPHQL 变量',
  'current_token': '当前 Token',
  'configure_new_token': '配置新 Token',
  'get_new_access_token': '获取新 Access Token',
  'enter_url_and_click_send': '输入 URL 并点击发送以获取响应',
  'requested_1_times': '已请求 1 次',
  'save_response_to_file': '保存响应到文件',
  'clear_response': '清除响应',
  'response_time': '响应时间',
  'request_size': '请求大小',
  'http_version': 'HTTP 版本',
  'local_address': '本地地址',
  'remote_address': '远程地址',
  'no_headers': '无请求头',
  'key': '密钥:',
  'no_cookies': '无 Cookies',
  'expires': '过期时间',
  'httponly': 'HttpOnly',
  'secure': 'Secure',
  'no_test_results': '无测试结果',
  'view_in_console': '在控制台查看',
  'save_to': '保存到 ',
  'save_request': '保存请求',
  'request_name': '请求名称',
  'description': '描述',
  'under_construction': '建设中...',
  'keyboard_shortcuts': '快捷键',
  'through': '通过',
  'export_data': '导出数据',
  'export_data_success': '数据导出成功！',
  'export_data_failed': '导出数据失败：',
  'import_data_success': '数据导入成功！',
  'import_data_failed': '导入数据失败：',
  'export_all_your_collectio': '将所有的集合、环境、全局变量和预设请求头导出为单个文件。',
  'import_your_data_from_a_p': '从之前的导出中导入数据。',
  'capture_proxy_mitm': '抓包代理 (MITM)',
  'enable_ssl_proxying': '启用 SSL 代理',
  'enable_ssl_proxying_desc': '解密 HTTPS 流量。需要安装 CA 证书。',
  'use_system_proxy': '使用系统代理',
  'use_system_proxy_desc': '使用系统代理发送请求。',
  'add_custom_proxy': '添加自定义代理配置',
  'proxy_server_hint': '例如 127.0.0.1:8080 或 http://proxy:80',
  'proxy_server': '代理服务器',
  'postlens': 'PostLens',
  'version_1_0_0': '版本 1.0.0',
  'grpc_request': 'gRPC 请求',
  'websocket_request': 'WebSocket 请求',
  'socket_request': 'Socket 请求',
  'mqtt_request': 'MQTT 请求',
  'clear_history': '清除历史',
  'add_request': '添加请求',
  'add_folder': '添加文件夹',
  'more': '更多',
  'new_folder': '新建文件夹',
  'secret_key': '密钥:',
  'public_key_pem': '公钥 (PEM):',
  'private_key_pem': '私钥 (PEM):',
  'key_config': '密钥 / 配置:',
  'generate_sm2_keys': '生成 SM2 密钥对',
  'app_secret': 'App Secret:',
  'generate_uuid_v1_time_bas': '生成 UUID v1 (基于时间)',
  'generate_uuid_v4_random': '生成 UUID v4 (随机)',
  'pattern': '正则表达式:',
  'qr_code_preview': '二维码预览',
  'export_image': '导出图片',
  'no_image_rendered': '无渲染图片',
  'create_new_workspace': '创建新工作区',
  'summary': '简介',
  'create_workspace': '创建工作区',

  'settings': '设置',
  'general': '常规',
  'themes': '主题',
  'shortcuts': '快捷键',
  'data': '数据',
  'proxy': '代理',
  'about': '关于',
  'theme': '主题',
  'test_results': '测试结果',
  'request_timeout': '请求超时',
  'request_timeout_desc': '设置请求在超时前应等待响应的时间。若从不超时，请设置为0。',
  'max_response_size': '最大响应大小',
  'max_response_size_desc': '设置要下载的响应的最大大小。若要下载任何大小的响应，请设置为0。',
  'ssl_cert_verification': 'SSL 证书验证',
  'disable_cookies_setting': '禁用 Cookies',
  'disable_cookies_desc': '为所有请求禁用 cookie jar。',
  'send_no_cache_header': '发送 no-cache 请求头',
  'system_mode': '跟随系统',
  'light_mode': '浅色模式',
  'dark_mode': '深色模式',

  // Shortcuts
  'Tabs': '标签页',
  'Sidebar': '侧边栏',
  'Request': '请求',
  'Interface': '界面',
  'Window and modals': '窗口与弹窗',
  'Close Tab': '关闭标签页',
  'Force Close Tab': '强制关闭标签页',
  'Switch To Next Tab': '切换到下一个标签页',
  'Switch To Previous Tab': '切换到上一个标签页',
  'Switch To Tab at Position': '切换到指定位置标签页',
  'Switch To Last Tab': '切换到最后一个标签页',
  'Reopen Last Closed Tab': '重新打开最后关闭的标签页',
  'New Runner Tab': '新建 Runner 标签页',
  'Search Tabs': '搜索标签页',
  'Search Sidebar': '搜索侧边栏',
  'Next Item': '下一个项目',
  'Previous Item': '上一个项目',
  'Expand Item': '展开项目',
  'Expand All': '展开全部',
  'Collapse Item': '折叠项目',
  'Collapse All': '折叠全部',
  'Select Item': '选择项目',
  'Rename Item': '重命名项目',
  'Cut Item': '剪切项目',
  'Copy Item': '复制项目',
  'Paste Item': '粘贴项目',
  'Duplicate Item': '复制项目',
  'Delete Item': '删除项目',
  'Request URL': '请求 URL',
  'Save Request As': '另存请求为',
  'Send Request': '发送请求',
  'Send And Download Request': '发送并下载请求',
  'Send Request with AI': '使用 AI 发送请求',
  'Zoom In': '放大',
  'Zoom Out': '缩小',
  'Reset Zoom': '重置缩放',
  'Toggle Two-Pane View': '切换双窗格视图',
  'Toggle Left Sidebar': '切换左侧边栏',
  'Toggle Right Sidebar': '切换右侧边栏',
  'Toggle Workbench': '切换工作台',
  'Swap Sidebars': '交换侧边栏',
  'Reset Layout': '重置布局',
  'Environment Selector': '环境选择器',
  'New...': '新建...',
  'New PostLens Window': '新建 PostLens 窗口',
  'New Console Window': '新建控制台窗口',
  'Find': '查找',
  'Open Shortcut Help': '打开快捷键帮助',
  'Search in Current Workspace': '在当前工作区搜索',
  'Open Agent Mode': '打开 Agent 模式',
  'Open Vault': '打开保险库',
  'Cancel Conversation': '取消对话',
  'Accept All': '全部接受',
  'Reject All': '全部拒绝',

  'language': '语言',
  'english': '英文',
  'chinese': '中文',
  'close': '关闭',
  'my_workspace': '我的工作区',
  'home': '主页',
  'workspaces': '工作区',
  'api_network': 'API 网络',
  'search': '搜索',
  'no_environment': '无环境',
  'new_environment': '新环境',
  'no_collections': '暂无集合',
  'no_history': '暂无历史记录',
  'no_files': '暂无文件',
  'no_tools': '暂无工具',
  'no_workspaces': '暂无工作空间',
  'all_workspaces': '所有工作空间',
  'view_all_workspaces': '查看所有工作空间',
  'new_request': '新建请求',
  'send': '发送',
  'params': '参数',
  'authorization': '鉴权',
  'headers': '请求头',
  'body': '请求体',
  'pre_request_script': '前置脚本',
  'tests': '测试',
  'collections': '集合',
  'environments': '环境',
  'history': '历史',
  'files': '文件',
  'filter': '过滤',
  'new_collection': '新建集合',
  'http_request': 'HTTP 请求',
  'request_history': '请求历史',
  'clear_all': '清除全部',
  'import': '导入',
  'save_responses': '保存响应',
  'status': '状态',
  'time': '时间',
  'size': '大小',
  'response_body': '响应体',
  'cookies': 'Cookies',
  'console': '控制台',
  'clear': '清除',
  'cancel': '取消',
  'save': '保存',
  'create': '创建',
  'create_variable': '创建',
  'current_environment': '当前环境',
  'enter_value': '输入值',
  'please_enter_value': '请输入值',
  'empty': '空',
  'environment': '环境',
  'global': '全局',
  'rename': '重命名',
  'duplicate': '复制',
  'delete': '删除',
  'overview': '概览',
  'environment_coming_soon': '环境功能即将推出',
  'capture': '抓包',
  'overview_tab': '总览',
  'raw_tab': '原始',
  'headers_tab': '请求头',
  'body_tab': '请求体',
  'raw_request_data': '原始请求数据',
  'body_empty_or_binary': '请求体为空或二进制',
  'method': '方法',
  'protocol': '协议',
  'server_address': '服务端地址',
  'stream': '流',
  'proxy_protocol': '代理协议',
  'application': '应用程序',
  'name': '名称',
  'path': '路径',
  'process_id': '进程ID',
  'connection': '连接',
  'frontend': '前端',
  'client_address': ' - 客户端 地址',
  'client_port': ' - 客户端 端口',
  'server_address_sub': ' - 服务端 地址',
  'server_port': ' - 服务端 端口',
  'backend': '后端',
  'version': '版本',
  'select_alpn': '选择ALPN',
  'cipher_suite_list': '加密算法列表',
  'select_cipher_suite': '选择算法',
  'request_start': '请求开始',
  'request_end': '请求结束',
  'total_duration': '总时长',
  'request': '请求',
  'response': '响应',
  'total': '总计',
  'cannot_parse_color': '无法解析颜色格式',
  'copied': '已复制',
  'color_palette_conversion': '调色盘 / 多格式转换',
  'input_color_support': '输入颜色（支持 HEX / RGB / HSL / CMYK）',
  'preview': '预览',
  'edit': '编辑',
  'rich_text': '富文本',
  'markdown': 'Markdown',
  'doc': '文档',
  'preset_palette': '预设调色盘',
  'copy_hex': '复制 HEX',
  'reset': '重置',
  'copy': '复制',
  'base64_encode_decode': 'Base64 编解码',
  'url_encode_decode': 'URL 编解码',
  'jwt_decode': 'JWT 解析',
  'json_escape': 'JSON 转义',
  'sm_algorithms': '国密 (SM2/SM3/SM4) 算法',
  'api_signature_verification': '接口签名校验 (Demo: Key sort + Secret + MD5)',
  'file_md5_calc': '文件 MD5 计算',
  'select_file': '选择文件',
  'file_path_label': '文件路径: ',
  'md5_result_label': 'MD5 结果:',
  'rsa_encrypt_decrypt': 'RSA 加解密',
  'seconds': '秒(s)',
  'milliseconds': '毫秒(ms)',
  'current_timestamp': '当前时间戳',
  'second_unit': '秒',
  'millisecond_unit': '毫秒',
  'switch_unit': '切换单位',
  'start': '开始',
  'stop': '停止',
  'single_conversion': '单个转换',
  'batch_conversion': '批量转换',
  'ts_to_datetime': '时间戳转日期时间',
  'convert': '转换',
  'conversion_result': '转换结果',
  'datetime_to_ts': '日期时间转时间戳',
  'generate_quantity': '生成数量:',
  'uuid_generator': 'UUID 生成器',
  'regex_testing': '正则表达式测试',
  'text_to_qrcode': '文本 <-> 二维码',
  'json_format_minify': 'JSON 格式化/压缩',
  'xml_format': 'XML 格式化 (Simple)',
  'text_hex_dump': 'Text <-> Hex Dump',
  'image_base64': '图片 <-> Base64',
  'tool_encode_decode': '编解码',
  'tool_encrypt_decrypt': '加解密',
  'tool_view': '视图',
  'tool_other': '其他',
  'tool_base64': 'Base64',
  'tool_url': 'URL',
  'tool_jwt': 'JWT',
  'tool_json_escape': 'JSON转义',
  'tool_hash': 'Hash',
  'tool_file_md5': '文件 MD5',
  'tool_hmac': 'HMAC',
  'tool_aes': 'AES',
  'tool_rsa': 'RSA',
  'tool_sm': '国密 (SM)',
  'tool_api_signature': '接口签名校验',
  'tool_json': 'JSON',
  'tool_xml': 'XML',
  'tool_hex': 'Hex',
  'tool_image': '图片',
  'tool_color': '色彩',
  'tool_timestamp': '时间戳',
  'tool_uuid': 'UUID',
  'tool_regex': '正则表达式',
  'tool_qrcode': '二维码',
  'no_open_tabs': '当前没有打开的标签页',
  'quick_create_hint': '你可以快速创建新的请求或工作区，也可以导入已有数据继续工作。',
  'import_data': '导入数据',
  'open_workspace_overview': '打开工作区概览',
  'open_settings': '打开设置',
  'proxy_port': '代理端口',
  'system_proxy_enabled': '已联动开启',
  'system_proxy_disabled': '未开启',
  'start_capture_hint': '点击开始抓包后，将自动启动本地代理并尝试开启系统代理',
  'stop_capture': '停止抓包',
  'start_capture': '开始抓包',
  'proxy_conflict_title': '发现其他代理软件',
  'proxy_conflict_content': '系统当前已经开启了其他代理软件，可能会与抓包功能产生冲突。建议您先关闭其他代理软件，然后再试。',
  'got_it': '知道了',
  'system_proxy_is_on': '系统代理已开',
  'only_switch_proxy': '仅切换代理',
  'please_start_capture_first': '请先开始抓包',
  'cert_installed': '已安装证书',
  'install_root_cert': '安装根证书',
  'copy_current_item': '复制当前条目',
  'copied_to_clipboard': '已复制到剪贴板',
  'close_capture_page': '关闭抓包页面',
  'search_url_host': '搜索 URL / Host',
  'listening': '监听中',
  'not_started': '未启动',
  'no_data': '暂无数据',
  'icon': '图标',
  'status_code': '状态码',
  'server_ip': '服务器IP',
  'duration': '时长',
  'request_and_response': '请求 & 响应',
  'no': '无',
  'connect_tunnel_no_body': 'CONNECT 隧道无可读请求体',
  'no_request_body': '无请求体',
  'https_not_decrypted': 'HTTPS 内容未解密（当前为隧道模式）',
  'no_response_body': '无响应体',
  'search_coming_soon': '搜索功能即将上线',
  'save_data': '保存数据',
  'saved_to': '已保存至 ',
  'copy_curl': '复制 cURL',
  'curl_copied': 'cURL 已复制',
  'view_details': '查看详情',
  'select_request_view_details': '选择一条请求查看详情',
  'install_mitm_root_cert': '安装 MITM 根证书',
  'install_cert_desc': '为了能够解密 HTTPS 请求，您需要在系统中安装并信任我们的根证书。请执行以下步骤：',
  'cert_path': '证书路径：',
  'install_trust_command': '安装与信任命令：',
  'command_copied': '命令已复制到剪贴板',
  'install_cert_hint': '提示：执行完成后，可能需要重启浏览器或相关应用程序以使证书生效。',
  'auto_execute_command': '自动执行 (需权限)',
  'auto_command_not_supported': '暂不支持该操作系统的自动命令生成',
  'linux_manual_execute': 'Linux 请手动在终端执行上述命令',
  'cert_install_success': '证书安装成功！',
  'install_failed': '安装失败：',
  'auth_type': '鉴权类型',
  'auth_header_auto_gen': '发送请求时将自动生成鉴权头。',
  'no_auth': '无鉴权',
  'no_auth_desc': '此请求不使用任何鉴权。',
  'token': '令牌',
  'username': '用户名',
  'password': '密码',
  'value': '值',
  'add_to': '添加到',
  'algorithm': '算法',
  'secret': '密钥',
  'secret_base64_encoded': '密钥 Base64 编码',
  'payload': '载荷',
  'advanced_configuration': '高级配置',
  'request_header_prefix': '请求头前缀',
  'jwt_headers': 'JWT 头部',
  'filter_application': '应用程序',
  'filter_domain': '域名',
  'filter_method': '请求方法',
  'filter_status_code': '状态码',
  'filter_resource_type': '资源类型',
  'filter_contains': '包含',
  'filter_equals': '等于',
  'filter_not_equals': '不等于',
  'filter_not_contains': '不包含',
  'add_filter_condition': '添加筛选条件',
  'no_filters': '暂无筛选条件。',
  'remove_filter': '移除',
  'add_filter': '添加',
  'global_variables': '全局变量',
  'global_variables_desc': '这些变量在所有请求中可用。使用 {{变量名}} 语法来引用它们。',
  'show_timestamps': '显示时间戳',
  'hide_network': '隐藏网络请求',

  // Tool Strings
  'text_utf8': '文本 (UTF-8)',
  'enter_text_here': '在此输入文本...',
  'base64': 'Base64',
  'enter_base64_here': '在此输入 Base64...',
  'encode': '编码',
  'decode': '解码',
  'error_encoding': '编码错误: ',
  'error_decoding': '解码错误: ',
  'hash': '哈希',
  'enter_text_to_hash': '输入要计算哈希的文本...',
  'hex': '十六进制',
  'text': '文本',
  'hex_dump': 'Hex Dump',
  'text_to_hex': '文本 -> Hex',
  'hex_to_text': 'Hex -> 文本',
  'error_decoding_hex': '解码 Hex 错误: ',
  'invalid_hex_length': '无效的 hex 字符串长度',
  'aes_key_hint': 'AES 密钥（自动填充至 32 字符）',
  'iv_hint': 'IV（自动填充至 16 字符）',
  'aes_cbc_pkcs7': 'AES (CBC/PKCS7)',
  'plaintext': '明文',
  'text_to_encrypt': '要加密的文本',
  'ciphertext_base64': '密文 (Base64)',
  'base64_ciphertext': 'Base64 密文',
  'encrypt': '加密',
  'decrypt': '解密',
  'error': '错误: ',
  'hmac': 'HMAC',
  'enter_text_to_sign': '输入要签名的文本...',
  'hmac_hex': 'HMAC 十六进制',
  'compute_hmac': '计算 HMAC',
  'image_base64_label': '图片 Base64',
  'render_image': '渲染图片',
  'select_image': '选择图片',
  'invalid_image_base64': '无效的图片 Base64: ',
  'image_exported_successfully': '图片导出成功！',
  'failed_to_export_image': '导出图片失败: ',
  'failed_to_select_image': '选择图片失败: ',
  'save_image': '保存图片',
  'unescaped_string': '未转义字符串',
  'escaped_string': '已转义字符串',
  'escape': '转义',
  'unescape': '反转义',
  'error_escaping': '转义错误: ',
  'error_unescaping': '反转义错误: ',
  'raw_json': '原始 JSON',
  'formatted_json': '格式化 JSON',
  'minify': '压缩',
  'invalid_json': '无效的 JSON: ',
  'jwt_token': 'JWT 令牌',
  'decoded_payload': '解码载荷',
  'invalid_jwt_token': '无效的 JWT 令牌（必须由点分隔的 3 部分组成）',
  'error_decoding_jwt': '解码 JWT 错误: ',
  'unit': '单位',
  'timezone': '时区',
  'generated_uuids': '生成的 UUID',
  'test_text': '测试文本',
  'matches': '匹配结果',
  'test_match': '测试匹配',
  'please_enter_pattern': '请输入正则表达式',
  'no_matches_found': '未找到匹配项。',
  'found_matches': '找到匹配项：\n',
  'match': '匹配',
  'group': '分组',
  'regex_error': '正则表达式错误: ',
  'text_url': '文本 / URL',
  'enter_text_to_generate_qr': '输入要生成二维码的文本',
  'generate_qr': '生成二维码',
  'recognize_qr': '识别二维码',
  'failed_to_recognize_qr': '识别二维码失败: ',
  'save_qr_code': '保存二维码',
  'qr_code_exported_successfully': '二维码导出成功！',
  'failed_to_export_qr': '导出二维码失败: ',
  'encrypt_with_public': '加密 (使用公钥)',
  'decrypt_with_private': '解密 (使用私钥)',
  'encryption_error': '加密错误: ',
  'decryption_error': '解密错误: ',
  'enter_32_char_hex_key': '输入32字符的Hex密钥用于SM4，或点击生成用于SM2',
  'generated_sm2_key_pair': '已生成 SM2 密钥对',
  'error_generating_keys': '生成密钥错误: ',
  'sm4_key_must_be_32_hex': 'SM4 密钥必须正好是 32 个十六进制字符（16字节）。',
  'please_generate_sm2_keys_first': '请先生成 SM2 密钥。',
  'input_data': '输入数据',
  'output_result': '输出结果',
  'compute': '计算',
  'decoded_text': '解码文本',
  'url_encode_hint_1': 'https://example.com/?q=test',
  'encoded_url': '编码 URL',
  'url_encode_hint_2': 'https%3A%2F%2Fexample.com%2F%3Fq%3Dtest',
  'raw_xml': '原始 XML',
  'formatted_xml': '格式化 XML',
  'error_formatting_xml': '格式化 XML 错误: ',
  'input_color_hint':
      '#FF0000 / rgb(255,0,0) / hsl(0,100%,50%) / cmyk(0%,100%,100%,0%)',
  'calculating': '计算中...',

  // WebSocket, Socket, MQTT pages
  'ws': 'WS',
  'connect': '连接',
  'disconnect': '断开',
  'connected': '已连接',
  'disconnected': '已断开',
  'connected_to': '已连接到',
  'disconnected_from': '已从服务器断开',
  'connection_closed_by_server': '服务器关闭了连接',
  'failed_to_connect': '连接失败',
  'connect_error': '连接错误',
  'message': '消息',
  'messages': '消息',
  'all_messages': '全部消息',
  'clear_messages': '清空消息',
  'enter_message_here': '在此输入消息',
  'format': '格式化',
  'show_auto_headers': '显示自动生成的请求头',
  'hide_auto_headers': '隐藏自动生成的请求头',
  'auto_generated': '自动生成',
  'enable_cert_verification': '启用服务器证书验证',
  'cert_verification_desc': '通过安全连接时验证服务器证书。',
  'handshake_timeout': '握手请求超时',
  'handshake_timeout_desc': '设置握手请求超时前的等待时间（毫秒）。设为0表示永不超时。',
  'reconnection_attempts': '重连次数',
  'reconnection_attempts_desc': '连接异常关闭时的最大重连次数。',
  'reconnection_intervals': '重连间隔',
  'reconnection_intervals_desc': '每次重连尝试之间的间隔时间（毫秒）。',
  'max_message_size': '最大消息大小',
  'max_message_size_desc': '允许的最大消息大小（MB）。设为0表示不限制大小。',
  'enter_url': '输入 URL',
  'select_protocol': '选择协议',
  'untitled_request': '未命名请求',
  'today': '今天',
  'yesterday': '昨天',

  // API Signature Tool
  'api_sign_cert_file': '证书文件',
  'api_sign_key_text': '密钥文本',
  'api_sign_choose_file': '选择文件',
  'api_sign_no_file_selected': '未选择文件',
  'api_sign_app_private_key': '应用私钥 (PEM)',
  'api_sign_params': '参数 (JSON) / 明文',
  'api_sign_charset': '字符集: ',
  'api_sign_type': '签名方式: ',
  'api_sign_start_sign': '开始签名',
  'api_sign_signature_result': '签名结果',
  'api_sign_platform_public_key': '平台公钥 (PEM)',
  'api_sign_notify_params': '通知参数 (JSON) / 明文',
  'api_sign_signature_to_verify': '待验签签名',
  'api_sign_signature_to_verify_hint': '如果 JSON 包含 "sign" 字段，此处可为空。',
  'api_sign_start_verify': '开始验签',
  'api_sign_verification_result': '验签结果',
  'api_sign_tab_sign': '签名',
  'api_sign_tab_verify': '验签',
  'api_sign_verify_success': '验签成功',
  'api_sign_verify_failed': '验签失败',
  'api_sign_error_private_key_empty': '私钥文本为空',
  'api_sign_error_cert_not_selected': '未选择证书文件',
  'api_sign_error_no_private_key_p12': 'P12 中未找到私钥',
  'api_sign_error_public_key_empty': '公钥文本为空',
  'api_sign_error_no_public_key_p12': 'P12 中未找到有效的公钥',
  'api_sign_error_signature_empty': '待验签签名为空',

  // Socket.IO specific
  'events': '事件',
  'listen': '监听',
  'add_event': '添加事件',
  'add_description': '添加描述',
  'compose_message': '编写消息',
  'event_name_default': '事件名称，默认为 "message"',
  'client_version': '客户端版本',
  'client_version_desc': '选择用于连接服务器的客户端版本。',
  'handshake_path': '握手路径',
  'handshake_path_desc': '设置握手请求时使用的服务器路径。',
  'connect_to_send': '连接以发送和接收消息',
  'ack_received': '收到确认',
  'arg': '参数',
  'ack': '确认',

  // MQTT specific
  'topics': '主题',
  'subscribe': '订阅',
  'add_topic': '添加主题',
  'properties': '属性',
  'last_will': '遗嘱消息',
  'basic_auth': 'Basic 认证',
  'retain': '保留',
  'will_delay': '遗嘱延迟',
  'mqtt_url_hint': 'mqtt://broker.hivemq.com:1883',
  'add_property': '添加属性',
  'add_value': '添加值',
  'topic_label': '主题',
  'unsubscribed_from': '已取消订阅',
  'subscribed_to': '已订阅',
  'qos': 'QoS',
  'parse_escape': '自动解析转义字符',
  'loop_send': '循环发送',
  'log_mode': '日志模式显示',
  'auto_wrap': '自动换行',
  'hide_receive': '不显示接收数据',
  'auto_scroll': '自动滚动',
  'http_version_label': 'HTTP版本',
  'http_version_desc': '选择发送请求时使用的 HTTP 版本。',
  'enable_ssl_verification': '启用 SSL 证书验证',
  'enable_ssl_verification_desc': '发送请求时验证 SSL 证书。验证失败将导致请求被中止。',
  'follow_redirects': '自动重定向',
  'follow_redirects_desc': '自动跟随 HTTP 3xx 响应进行重定向。',
  'follow_original_http_method': '保留原始 HTTP 方法',
  'follow_original_http_method_desc': '重定向时保留原始 HTTP 方法，而不是默认重定向为 GET。',
  'follow_authorization_header': '保留 Authorization 头部',
  'follow_authorization_header_desc': '重定向到不同主机名时保留 Authorization 头部。',
  'remove_referer_header': '重定向时移除 Referer 头部',
  'remove_referer_header_desc': '发生重定向时移除 Referer 头部。',
  'enable_strict_http_parser': '启用严格 HTTP 解析器',
  'enable_strict_http_parser_desc': '限制带有无效 HTTP 头部的响应。',
  'encode_url_automatically': '自动编码 URL',
  'encode_url_automatically_desc': '自动对 URL 的路径、查询参数和身份验证字段进行编码。',
  'disable_cookie_jar': '禁用 Cookie 容器',
  'disable_cookie_jar_desc':
      '防止此请求使用的 Cookie 存储在 Cookie 容器中。Cookie 容器中现有的 Cookie 也不会作为头部添加到此请求中。',
  'use_server_cipher_suite': '握手期间使用服务器密码套件',
  'use_server_cipher_suite_desc': '握手期间优先使用服务器的密码套件顺序，而不是客户端的顺序。',
  'max_redirects': '最大重定向次数',
  'max_redirects_desc': '设置跟随重定向的最大次数上限。',
  'disabled_protocols': '握手期间禁用的 TLS/SSL 协议',
  'disabled_protocols_desc': '指定握手期间禁用的 SSL 和 TLS 协议版本。其他所有协议将被启用。',
  'cipher_suite_selection': '密码套件选择',
  'cipher_suite_selection_desc': 'SSL 服务器配置文件用于建立安全连接的密码套件顺序。',
  'enter_cipher_suites': '输入密码套件',
  'receive_settings': '接收设置',
  'send_settings': '发送设置',
};
