// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`

String generateCa({required String privateKeyPem}) =>
    RustLib.instance.api.crateApiProxyGenerateCa(privateKeyPem: privateKeyPem);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProxyCore>>
abstract class ProxyCore implements RustOpaqueInterface {
  factory ProxyCore() => RustLib.instance.api.crateApiProxyProxyCoreNew();

  Stream<CaptureSession> setupStream();

  Future<int> start({required ProxyConfig config});

  Future<void> stop();
}

class CaptureSession {
  final String id;
  final PlatformInt64 startedAt;
  final String protocol;
  final String method;
  final String url;
  final String host;
  final int port;
  final int? statusCode;
  final String? statusMessage;
  final PlatformInt64 durationMs;
  final PlatformInt64 requestBytes;
  final PlatformInt64 responseBytes;
  final Map<String, List<String>> requestHeaders;
  final String requestBody;
  final Map<String, List<String>> responseHeaders;
  final String responseBody;
  final String? error;
  final String? clientIp;
  final int? clientPort;
  final String? serverIp;
  final String? processId;
  final String? appName;
  final String? appPath;

  const CaptureSession({
    required this.id,
    required this.startedAt,
    required this.protocol,
    required this.method,
    required this.url,
    required this.host,
    required this.port,
    this.statusCode,
    this.statusMessage,
    required this.durationMs,
    required this.requestBytes,
    required this.responseBytes,
    required this.requestHeaders,
    required this.requestBody,
    required this.responseHeaders,
    required this.responseBody,
    this.error,
    this.clientIp,
    this.clientPort,
    this.serverIp,
    this.processId,
    this.appName,
    this.appPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startedAt.hashCode ^
      protocol.hashCode ^
      method.hashCode ^
      url.hashCode ^
      host.hashCode ^
      port.hashCode ^
      statusCode.hashCode ^
      statusMessage.hashCode ^
      durationMs.hashCode ^
      requestBytes.hashCode ^
      responseBytes.hashCode ^
      requestHeaders.hashCode ^
      requestBody.hashCode ^
      responseHeaders.hashCode ^
      responseBody.hashCode ^
      error.hashCode ^
      clientIp.hashCode ^
      clientPort.hashCode ^
      serverIp.hashCode ^
      processId.hashCode ^
      appName.hashCode ^
      appPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startedAt == other.startedAt &&
          protocol == other.protocol &&
          method == other.method &&
          url == other.url &&
          host == other.host &&
          port == other.port &&
          statusCode == other.statusCode &&
          statusMessage == other.statusMessage &&
          durationMs == other.durationMs &&
          requestBytes == other.requestBytes &&
          responseBytes == other.responseBytes &&
          requestHeaders == other.requestHeaders &&
          requestBody == other.requestBody &&
          responseHeaders == other.responseHeaders &&
          responseBody == other.responseBody &&
          error == other.error &&
          clientIp == other.clientIp &&
          clientPort == other.clientPort &&
          serverIp == other.serverIp &&
          processId == other.processId &&
          appName == other.appName &&
          appPath == other.appPath;
}

class ProxyConfig {
  final int port;
  final bool enableSslProxying;
  final String? caCert;
  final String? caKey;

  const ProxyConfig({
    required this.port,
    required this.enableSslProxying,
    this.caCert,
    this.caKey,
  });

  @override
  int get hashCode =>
      port.hashCode ^
      enableSslProxying.hashCode ^
      caCert.hashCode ^
      caKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyConfig &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          enableSslProxying == other.enableSslProxying &&
          caCert == other.caCert &&
          caKey == other.caKey;
}
